"""The dashboard: a static site that restates what the repo already holds.

Two jobs, and they are the two the owner asked for.

**Explaining the shape of the work.** `build.py` reads the committed artefacts —
`eval/gold/`, `ontology/draft/`, `graph/`, `queries/`, `shapes/`, the ADR log,
the status board — and writes them as JSON that a browser renders. It derives
nothing: every number on the site is a count of something a reviewer signed or a
generator produced, and where a figure needs the pinned snapshot the site says
so instead of showing a stale one.

**Collecting the decisions only the owner can make.** `questions.py` reads
`review/questions/open-questions.yaml`, the plain-language queue of things
waiting on a person. The site renders it as a form; a submission becomes a
GitHub issue; `ruling.py` turns that issue into a file in `review/rulings/` that
the next session reads. Nothing here decides anything — it asks, and it records
the answer verbatim.

The site has no build step, no package manager and no framework. Everything
under `site/data/` is generated by `tmk-dashboard --write`; everything else in
`site/` is hand-written and stays small on purpose.
"""

from __future__ import annotations

__all__ = ["build", "blocks", "questions", "ruling", "sources"]
