"""Generate the dashboard's data from what the repo already holds.

Every figure on the site is a count of something a reviewer signed or a
generator produced. This module reads **committed artefacts only** — the gold
set, the draft ontology, the two serialised graphs, the queries, the shapes, the
ADR log, the status board, the pin manifest — and never the pinned snapshot. That
line is deliberate and it is what makes the site deployable from a bare checkout:
a page build cannot fail because upstream was unreachable, and it cannot show a
number it did not measure.

The consequence is stated rather than hidden. Figures that live only in the
source graph (216 chunks, 529 citations, 16,405 triples) are **not restated
here**; the site renders `data/derived/reports/ontology.md` instead, which is
produced by the run that has the snapshot. The site restates nothing it can
render.

Output is one JSON file per page under `site/data/`, each in the block
vocabulary of `blocks.py`. `--check` regenerates in memory and diffs against
what is committed, ignoring only the generated-on stamp, so a content change
that was never reflected on the site fails CI rather than going quietly stale.
"""

from __future__ import annotations

import json
import re
import shutil
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Any, Iterable
from urllib.parse import unquote

from rdflib import Graph, URIRef
from rdflib.namespace import OWL, RDF, RDFS, SH

from tm_knowledge.config import DEFAULT_BASE_IRI, PIN_PATH, REPO_ROOT
from tm_knowledge.dashboard import blocks, questions as questions_module, sources
from tm_knowledge.ontology import ask as ask_module
from tm_knowledge.ontology import rules as rules_module
from tm_knowledge.ontology import tbox, validate
from tm_knowledge.stage0 import goldset

__all__ = ["SITE_DIR", "DATA_DIR", "PAGES", "build", "write", "check"]

SITE_DIR = REPO_ROOT / "site"
DATA_DIR = SITE_DIR / "data"
REPORTS_DIR = REPO_ROOT / "data" / "derived" / "reports"

REPO_URL = "https://github.com/Thomas-Amann-IPAustralia/TM-Knowledge"
BLOB = f"{REPO_URL}/blob/main"

#: Page id -> (nav label, one-line blurb). The order is the navigation order.
PAGES: tuple[tuple[str, str, str], ...] = (
    ("overview", "Overview", "What this is, and where it stands today"),
    ("inbox", "Your decisions", "Questions waiting on you, and what happens to your answers"),
    ("vocabulary", "Vocabulary", "The 52 approved legal ideas and how they relate"),
    ("ontology", "The model", "Classes, predicates and the nine draft modules"),
    ("graph", "The graph", "What is stored, and the trust metadata on every claim"),
    ("questions", "Questions", "What the system must answer, and what it can answer today"),
    ("limits", "Limits", "What it cannot do, and what it must never say"),
    ("decisions", "Decisions", "Every choice on the record, and who made it"),
    ("reports", "Reports", "The generated status reports, rendered in full"),
)

#: Reports copied next to the site so a block can fetch them. They are already
#: committed under `data/derived/reports/`; committing a second copy would put
#: the same text in the history twice, so `site/data/reports/` is git-ignored
#: and rebuilt by every `--write`.
REPORTS: tuple[tuple[str, str, str], ...] = (
    ("ontology.md", "The ontology draft — what it holds and what it cannot answer",
     "Generated by `tmk-ontology-report`. Read section 5 if you read nothing else."),
    ("coverage.md", "Stage 0 coverage — what the evaluation set still needs",
     "Generated by `tmk-coverage`. An hour of expert time should visibly move a number here."),
    ("blockers.md", "The review queue, as the graph it is",
     "Generated by `tmk-blockers`. Which decision releases the most held records."),
    ("recon.md", "Corpus reconnaissance — where the section 43 material sits",
     "Generated by `tmk-recon` against the pinned snapshot."),
    ("rule-0001-flags.md", "RULE-0001 — every passage it flags, in full",
     "Generated by `tmk-flags`. What you asked to see on OQ-0003, and the count you were "
     "given was wrong: five passages, not 71."),
    ("concept-typing.md", "The 52 concepts, laid out for sorting",
     "Generated by `tmk-typing`. The evidence to sort by — what each concept is called, "
     "what it is explicitly not, and the passages it came from."),
    ("boundary.md", "Where section 43 stops — the boundary, computed",
     "Generated by `tmk-boundary` from your one-hop rule, including where the Manual's "
     "own citation habits stop it doing what you expected."),
)

_MARKER = re.compile(r"\{\{([^{}]+)\}\}")


class BuildError(RuntimeError):
    """The site could not be generated from what the repo holds."""


# --------------------------------------------------------------------- facts


@dataclass(frozen=True)
class Facts:
    """Everything read off disk, once, before any page is composed."""

    gold: goldset.GoldSet
    modules: dict[str, Graph]
    tbox: Graph
    approved: Graph
    inferred: Graph
    shapes: dict[str, Graph]
    queries: tuple[ask_module.CompetencyQuery, ...]
    rules: tuple[rules_module.Rule, ...]
    pin: dict[str, Any]
    adrs: tuple[sources.Adr, ...]
    stages: tuple[sources.Stage, ...]
    glossary: dict[str, dict[str, str]]
    questions: questions_module.QuestionSet
    rulings: tuple[questions_module.Ruling, ...]


def _read_graph(path: Path) -> Graph:
    if not path.exists():
        raise BuildError(
            f"{path.relative_to(REPO_ROOT)} is missing. The dashboard restates committed "
            f"artefacts; it does not rebuild them. Run `tmk-graph --write --rules` first."
        )
    graph = Graph()
    graph.parse(path, format="turtle")
    return graph


def gather() -> Facts:
    modules = {}
    for path in tbox.module_paths():
        graph = Graph()
        graph.parse(path, format="turtle")
        modules[path.name] = graph

    shapes = {}
    for name in validate.SHAPE_FILES:
        graph = Graph()
        graph.parse(REPO_ROOT / "shapes" / name, format="turtle")
        shapes[name] = graph

    return Facts(
        gold=goldset.load(),
        modules=modules,
        tbox=tbox.load(),
        approved=_read_graph(REPO_ROOT / "graph" / "approved.ttl"),
        inferred=_read_graph(REPO_ROOT / "graph" / "inferred.ttl"),
        shapes=shapes,
        queries=ask_module.load_queries(),
        rules=rules_module.load_rules(),
        pin=json.loads(PIN_PATH.read_text(encoding="utf-8")),
        adrs=sources.read_decisions(),
        stages=sources.read_stage_board(),
        glossary=sources.read_glossary(),
        questions=questions_module.load(),
        rulings=questions_module.load_rulings(),
    )


# ------------------------------------------------------------------- helpers


def _local(term: Any) -> str:
    """The readable tail of an IRI: `tmk:LegalConcept` -> `LegalConcept`."""
    text = str(term)
    if text.startswith(DEFAULT_BASE_IRI + "ref/"):
        return unquote(text[len(DEFAULT_BASE_IRI) + 4 :])
    return re.split(r"[#/]", text.rstrip("/"))[-1]


def _label(graph: Graph, subject: URIRef) -> str:
    value = graph.value(subject, RDFS.label)
    return str(value) if value else _local(subject)


def _comment(graph: Graph, subject: URIRef) -> str:
    value = graph.value(subject, RDFS.comment)
    return " ".join(str(value).split()) if value else ""


def _count(records: Iterable[dict[str, Any]]) -> int:
    return sum(1 for _ in records)


def _band(count: int, low: int, high: int) -> str:
    if count < low:
        return "gap"
    if count > high:
        return "warn"
    return "good"


def _ref_links(refs: Iterable[str]) -> dict[str, Any]:
    return blocks.chips(refs, tone="muted")


def _instances(graph: Graph) -> dict[str, int]:
    """How many things carry each class, in the approved graph."""
    counts: dict[str, int] = {}
    for _, _, cls in graph.triples((None, RDF.type, None)):
        counts[_local(cls)] = counts.get(_local(cls), 0) + 1
    return counts


# --------------------------------------------------------------------- pages


def _overview(facts: Facts) -> dict[str, Any]:
    gold = facts.gold
    asked = len(facts.questions.asked)
    unapplied = [ruling for ruling in facts.rulings if not ruling.is_applied]
    classes = sum(1 for _ in facts.tbox.subjects(RDF.type, OWL.Class))
    populated = _instances(facts.approved)

    page: dict[str, Any] = {
        "id": "overview",
        "title": "A knowledge base for section 43",
        "lede": (
            "This project is turning the part of the Trade Marks Manual that deals with "
            "**section 43** — marks with a connotation likely to deceive or cause confusion — "
            "into something a machine can reason over without ever deciding a case. "
            "Everything here was signed off by a person before it was modelled. "
            "Nothing on this page was written by an AI as legal content."
        ),
        "blocks": [],
    }

    if asked:
        page["blocks"].append(
            blocks.callout(
                "warn",
                f"{asked} decisions are waiting on you",
                "Six of them unblock the next piece of work. Each is written to be answerable "
                "without reading anything else, and your answers come back into the repository "
                "as a file the next session reads.",
                links=[{"label": "Go to your decisions", "href": "#/inbox"}],
            )
        )
    if unapplied:
        page["blocks"].append(
            blocks.callout(
                "good",
                f"{len(unapplied)} of your answers have not been acted on yet",
                "They are recorded and waiting for the next working session to pick up.",
                links=[{"label": "See what you answered", "href": "#/inbox"}],
            )
        )

    page["blocks"] += [
        blocks.stats(
            [
                {"label": "Approved records", "value": gold.total,
                 "note": "every one signed by a named reviewer, with a date", "tone": "good"},
                {"label": "Legal ideas", "value": gold.count("gold_concept"),
                 "note": "target 50–100", "tone": _band(gold.count("gold_concept"), 50, 100),
                 "href": "#/vocabulary"},
                {"label": "Relationships", "value": gold.count("gold_relationship"),
                 "note": "target 50–100", "tone": _band(gold.count("gold_relationship"), 50, 100)},
                {"label": "Named things found in the text", "value": gold.count("gold_entity"),
                 "note": "target 100–300", "tone": _band(gold.count("gold_entity"), 100, 300)},
                {"label": "Questions it must answer", "value": gold.count("competency_question"),
                 "note": f"{len(facts.queries)} answerable today", "href": "#/questions"},
                {"label": "Things it must never say", "value": gold.count("prohibited_use"),
                 "note": "tested as explicitly as the right answers", "href": "#/limits"},
            ],
            note="Counts are read from `eval/gold/` at build time. A target band comes from the "
                 "roadmap; a number below its band is shown as a gap, not smoothed over.",
        ),
        blocks.prose(
            "### How to read this site\n\n"
            "**Approved** means a named person signed a record on a date. That is the only "
            "kind of knowledge this project treats as true. Everything a machine proposes is a "
            "{{Candidate}} and is kept in a separate place, in a separate file, with a label on it.\n\n"
            "**Draft** means the model itself has not been approved. The nine {{Ontology}} modules "
            "are a proposal about how to describe this material; the content underneath them is "
            "signed, the shape around it is not.\n\n"
            "**The Manual is practice, not law.** It records what the Registrar does; it does not "
            "bind the Registrar's discretion and it is not legislation. Keeping those two apart is "
            "the single constraint most of this design exists to protect."
        ),
        blocks.stats(
            [
                {"label": "Model modules", "value": len(facts.modules), "note": "all draft, none approved"},
                {"label": "Classes declared", "value": classes,
                 "note": f"{sum(1 for name in _class_names(facts) if populated.get(name))} hold approved content"},
                {"label": "Predicates", "value": len(_predicates(facts)),
                 "note": "generated from approved relationships, never hand-written"},
                {"label": "Statements stored", "value": len(facts.approved),
                 "note": "each traceable to a signed record", "tone": "good"},
                {"label": "Machine-derived statements", "value": len(facts.inferred),
                 "note": "all quarantined — no rule is approved", "tone": "warn"},
                {"label": "Checks in the publication gate", "value": _shape_count(facts),
                 "note": "each with a fixture built to violate it"},
            ],
        ),
        blocks.prose("### Where each stage of the programme stands"),
        blocks.table(
            (("stage", "Stage"), ("name", "What it is"), ("status", "Status"), ("owner", "Owned by")),
            [
                {
                    "stage": stage.number,
                    "name": stage.name,
                    "status": {"chips": [{"label": stage.status, "tone": _stage_tone(stage.status)}]},
                    "owner": stage.owner,
                    "detail": [blocks.prose(stage.status_note)] if stage.status_note else [],
                }
                for stage in facts.stages
            ],
            note="From `docs/ROADMAP-STATUS.md`. Click a row for the detail behind the status.",
        ),
        blocks.callout(
            "note",
            "Where the numbers come from",
            f"Built from the repository at `main`, against the pinned upstream snapshot "
            f"`{facts.pin['commit'][:12]}` "
            f"({facts.pin['corpus']['pages']} Manual pages, {facts.pin['corpus']['chunks']:,} passages, "
            f"{facts.pin['corpus']['provisions']} legislative provisions). "
            "This site reads only files that are committed, so nothing here depends on a "
            "download succeeding — and figures that can only be measured with the full corpus "
            "are left to the generated reports rather than restated from memory.",
            links=[{"label": "The generated reports", "href": "#/reports"}],
        ),
    ]
    return page


def _stage_tone(status: str) -> str:
    return {"done": "good", "partial": "note", "not started": "gap"}.get(status, "muted")


def _class_names(facts: Facts) -> list[str]:
    return sorted({_local(cls) for cls in facts.tbox.subjects(RDF.type, OWL.Class)})


def _shape_count(facts: Facts) -> int:
    return sum(
        sum(1 for _ in graph.subjects(RDF.type, SH.NodeShape)) for graph in facts.shapes.values()
    )


def _predicates(facts: Facts) -> list[dict[str, Any]]:
    graph = facts.modules["relations.ttl"]
    tmk = DEFAULT_BASE_IRI + "ns/"
    found = []
    for subject in graph.subjects(RDF.type, OWL.ObjectProperty):
        used_by = sorted(str(value) for value in graph.objects(subject, URIRef(tmk + "usedBy")))
        count = graph.value(subject, URIRef(tmk + "usageCount"))
        found.append(
            {
                "name": _local(subject),
                "label": _label(graph, subject),
                "comment": _comment(graph, subject),
                "uses": int(count) if count is not None else 0,
                "used_by": used_by,
                "subject_types": sorted(
                    _local(value) for value in graph.objects(subject, URIRef(tmk + "observedSubjectType"))
                ),
                "object_types": sorted(
                    _local(value) for value in graph.objects(subject, URIRef(tmk + "observedObjectType"))
                ),
            }
        )
    return sorted(found, key=lambda entry: (-entry["uses"], entry["name"]))


def _ontology(facts: Facts) -> dict[str, Any]:
    populated = _instances(facts.approved)
    predicates = _predicates(facts)

    module_rows = []
    for name, graph in facts.modules.items():
        ontology = next(graph.subjects(RDF.type, OWL.Ontology), None)
        declared = sorted(_local(cls) for cls in graph.subjects(RDF.type, OWL.Class))
        holds = sum(populated.get(cls, 0) for cls in declared)
        module_rows.append(
            {
                "module": f"`{name}`",
                "what": _label(graph, ontology).replace("TM-Knowledge — ", "") if ontology else name,
                "classes": len(declared),
                "holds": {"chips": [{
                    "label": f"{holds:,} things" if holds else "nothing yet",
                    "tone": "good" if holds else "gap",
                }]},
                "detail": [
                    blocks.prose(_comment(graph, ontology) if ontology else ""),
                    blocks.listing([f"`{cls}`" + (f" — {populated[cls]:,}" if populated.get(cls) else " — empty")
                                    for cls in declared]) if declared else blocks.prose("Declares no classes."),
                ],
            }
        )

    class_rows = []
    for cls in sorted(facts.tbox.subjects(RDF.type, OWL.Class)):
        name = _local(cls)
        held = populated.get(name, 0)
        class_rows.append(
            {
                "name": f"`{name}`",
                "label": _label(facts.tbox, cls),
                "holds": {"chips": [{
                    "label": f"{held:,}" if held else "empty",
                    "tone": "good" if held else "gap",
                }]},
                "search": f"{name} {_label(facts.tbox, cls)} {_comment(facts.tbox, cls)}",
                "detail": [blocks.prose(_comment(facts.tbox, cls) or "_No description recorded._")],
            }
        )

    return {
        "id": "ontology",
        "title": "The model",
        "lede": (
            "An {{Ontology}} is the shape, not the content: which kinds of thing may exist, what may "
            "be said about each, and what may safely be inferred. Nine modules make up this one. "
            "**None of them is approved** — they live in `ontology/draft/` and move out one at a "
            "time, by a recorded human decision."
        ),
        "blocks": [
            blocks.callout(
                "note",
                "In one paragraph, for a reader who does not do this for a living",
                "The model is written in {{OWL 2 RL}}, a standard language for describing kinds of "
                "thing and the rules between them. The **RL** part is a deliberate restriction: it "
                "trades expressive power for the guarantee that reasoning finishes quickly and "
                "predictably. Separately, {{SHACL}} states constraints that must hold before "
                "anything is published — think of {{OWL 2 RL}} as what the model *means* and "
                "{{SHACL}} as what it *refuses to let through*.",
            ),
            blocks.stats(
                [
                    {"label": "Modules", "value": len(facts.modules), "note": "all draft"},
                    {"label": "Classes declared", "value": len(class_rows)},
                    {"label": "Classes with no approved content", "value":
                        sum(1 for row in class_rows if row["holds"]["chips"][0]["label"] == "empty"),
                     "note": "measured over the approved graph alone", "tone": "gap"},
                    {"label": "Predicates", "value": len(predicates),
                     "note": "the closed list extraction may use"},
                    {"label": "Predicates used once", "value": sum(1 for p in predicates if p["uses"] == 1),
                     "note": "a term seen once is a term nobody has tested", "tone": "warn"},
                ]
            ),
            blocks.prose("### The nine modules"),
            blocks.table(
                (("module", "File"), ("what", "What it covers"), ("classes", "Classes"), ("holds", "Currently holds")),
                module_rows,
                note="Click a row for the module's own description and the classes it declares.",
            ),
            blocks.prose(
                "### The predicates\n\n"
                "A {{Predicate}} is the middle of a statement — *this passage **states** that "
                "concept*. The list is **generated** from the relationships an expert approved, and "
                "a test compares the file against a regeneration. That is deliberate: a hand-written "
                "list of allowed relationships would be an agent choosing the vocabulary of the "
                "domain. To add one, have a reviewer approve a relationship that uses it."
            ),
            blocks.table(
                (("label", "Reads as"), ("name", "In the data"), ("uses", "Approved uses"),
                 ("seen", "Seen connecting")),
                [
                    {
                        "label": entry["label"],
                        "name": f"`{entry['name']}`",
                        "uses": {"chips": [{
                            "label": str(entry["uses"]),
                            "tone": "warn" if entry["uses"] == 1 else "good",
                        }]},
                        "seen": " → ".join(
                            ["/".join(entry["subject_types"]) or "—", "/".join(entry["object_types"]) or "—"]
                        ),
                        "search": f"{entry['label']} {entry['name']}",
                        "detail": [
                            blocks.prose(entry["comment"]),
                            blocks.prose(f"Used by: {', '.join(f'`{r}`' for r in entry['used_by'])}"),
                        ],
                    }
                    for entry in predicates
                ],
                search=True,
                note="The types in the last column are **observations**, not rules. Asserting them "
                     "as rules would silently reclassify everything they touch, so they are recorded "
                     "and infer nothing. Tightening one is an expert's ruling.",
            ),
            blocks.prose("### Every class in the model"),
            blocks.table(
                (("name", "Class"), ("label", "Reads as"), ("holds", "Approved instances")),
                class_rows,
                search=True,
                note="Counted over the approved graph only — the one this repository commits. The "
                     "source graph, which is rebuilt rather than stored, populates several more "
                     "(passages, citations, decisions); the ontology report counts those. An empty "
                     "class is a slot waiting for content, not a bug: the four that matter most — "
                     "ground of refusal, legal test, relevant factor, exception — are empty because "
                     "sorting the 52 legal ideas into them is a legal judgement.",
            ),
        ],
    }


def _vocabulary(facts: Facts) -> dict[str, Any]:
    concepts = facts.gold["gold_concept"]
    by_id = {record["id"]: record for record in concepts}

    def label_of(identifier: str) -> str:
        record = by_id.get(identifier)
        return f"{record['pref_label']}" if record else identifier

    flat = [
        record for record in concepts
        if not record.get("broader") and not record.get("narrower")
    ]

    rows = []
    for record in concepts:
        alt = record.get("alt_labels") or []
        not_labels = record.get("not_labels") or []
        detail: list[dict[str, Any]] = []
        if alt:
            detail.append(blocks.prose("**Also called:** " + ", ".join(f"*{value}*" for value in alt)))
        if not_labels:
            detail.append(
                blocks.callout(
                    "warn",
                    "Must not be confused with",
                    ", ".join(f"*{value}*" for value in not_labels)
                    + "\n\nA not-label is a term this concept is **not**. It is the part of the "
                      "vocabulary that stops a search quietly widening a legal test.",
                )
            )
        for field, heading in (("broader", "Sits under"), ("narrower", "Contains"), ("related", "Related to")):
            values = record.get(field) or []
            if values:
                detail.append(blocks.prose(f"**{heading}:** " + ", ".join(label_of(v) for v in values)))
        if record.get("definition_sources"):
            detail.append(
                blocks.prose(
                    "**Meaning drawn from:** "
                    + ", ".join(f"`{ref}`" for ref in record["definition_sources"])
                    + "\n\nThe passages the meaning comes from are recorded; **the meaning itself is "
                      "not written down anywhere.** Writing a definition would be authoring legal "
                      "content, so the record carries sources and no text."
                )
            )
        if record.get("legislative_basis"):
            detail.append(blocks.prose("**Legislative basis:** "
                                       + ", ".join(f"`{ref}`" for ref in record["legislative_basis"])))
        if record.get("notes"):
            detail.append(blocks.callout("note", "Reviewer's note", str(record["notes"])))
        detail.append(blocks.prose(
            f"_Approved by **{record.get('approved_by', '—')}** on {record.get('approved_date', '—')}._"
        ))

        rows.append(
            {
                "id": f"`{record['id']}`",
                "label": record["pref_label"],
                "alt": _ref_links(alt) if alt else "—",
                "place": {"chips": [{
                    "label": "in a hierarchy" if (record.get("broader") or record.get("narrower")) else "standalone",
                    "tone": "good" if (record.get("broader") or record.get("narrower")) else "gap",
                }]},
                "anchor": record["id"],
                "search": " ".join([record["id"], record["pref_label"], *alt, *not_labels]),
                "detail": detail,
            }
        )

    return {
        "id": "vocabulary",
        "title": "The vocabulary",
        "lede": (
            f"{len(concepts)} legal ideas, each drawn from the section 43 material and each signed "
            "off by a named reviewer. Held as {{SKOS}} — a standard for controlled vocabularies: a "
            "preferred label, the variants that mean the same thing, and the ones that do not."
        ),
        "blocks": [
            blocks.stats(
                [
                    {"label": "Approved ideas", "value": len(concepts), "note": "target 50–100", "tone": "good"},
                    {"label": "With a definition written down", "value": 0,
                     "note": "sources recorded, text never authored", "tone": "note"},
                    {"label": "Standing outside any hierarchy", "value": len(flat),
                     "note": "a flat list is a list with extra steps", "tone": "gap"},
                    {"label": "Sorted into a kind", "value": 0,
                     "note": "ground of refusal / test / factor / exception", "tone": "gap"},
                ]
            ),
            blocks.callout(
                "gap",
                "The biggest single gap, and it needs one pass by one person",
                f"All {len(concepts)} ideas sit in the model as a bare *legal concept*. Whether "
                "*connotation* is a **test** the decision maker applies or a **factor** feeding into "
                "one is a legal judgement, so the four slots for it are declared and empty. "
                "Filling them is one pass over a list for someone who knows the domain, and it is "
                "what turns a flat vocabulary into something later stages can generalise over.",
                links=[{"label": "This is question 1 in your queue", "href": "#/inbox"}],
            ),
            blocks.table(
                (("id", "ID"), ("label", "Preferred label"), ("alt", "Also called"), ("place", "Placement")),
                rows,
                search=True,
                note="Search matches the label, its variants and the terms it must not be confused "
                     "with. Click a row for the full record.",
            ),
        ],
    }


def _graph_page(facts: Facts) -> dict[str, Any]:
    populated = _instances(facts.approved)
    corpus = facts.pin["corpus"]

    rule_cards = [
        {
            "title": rule.rule_id,
            "subtitle": rule.derives,
            "text": f"**Stands on:** {rule.basis}\n\n**Does not establish:** {rule.limits}",
            "badges": [
                {"label": "approved" if rule.is_approved else "not approved",
                 "tone": "good" if rule.is_approved else "warn"},
                {"label": "output quarantined", "tone": "note"} if not rule.is_approved else
                {"label": "output usable", "tone": "good"},
            ],
            "links": [{"label": "Read the rule", "href": f"{BLOB}/queries/rules/{rule.path.name}"}],
        }
        for rule in facts.rules
    ]

    return {
        "id": "graph",
        "title": "The graph",
        "lede": (
            "A {{Knowledge graph}} stores knowledge as small statements — a subject, a "
            "relationship, an object — rather than as rows in a table. Each one is a {{Triple}}. "
            "The point is not the format; it is that every statement can carry, alongside itself, "
            "the record of where it came from and who stands behind it."
        ),
        "blocks": [
            blocks.stats(
                [
                    {"label": "Approved statements", "value": len(facts.approved),
                     "note": "each traceable to a signed record", "tone": "good"},
                    {"label": "Machine-derived statements", "value": len(facts.inferred),
                     "note": "every one marked 'needs a human'", "tone": "warn"},
                    {"label": "Kinds of thing held", "value": len(populated),
                     "note": "of the classes the model declares"},
                ],
                note="Counted from `graph/approved.ttl` and `graph/inferred.ttl` as committed.",
            ),
            blocks.prose("### What the approved half holds"),
            blocks.table(
                (("thing", "Kind of thing"), ("count", "How many")),
                [
                    {"thing": f"`{name}`", "count": f"{count:,}"}
                    for name, count in sorted(populated.items(), key=lambda item: -item[1])
                ],
                note="Read off the committed file, so this table cannot claim something the data "
                     "does not contain.",
            ),
            blocks.prose(
                "### Four separate compartments, and the separation is the governance\n\n"
                "The store is divided into {{Named graph}}s, and nothing is in two of them. "
                "**Source** restates what the upstream extraction already recorded. **Approved** "
                "restates what a reviewer already signed. **Inferred** holds what a rule worked out, "
                "and everything in it is labelled as needing a human. A fourth compartment for "
                "machine-proposed candidates exists in the design and is empty, because no "
                "extraction has been run.\n\n"
                "Keeping them apart is what makes it possible to answer *who says so* about any "
                "statement in the system — and to answer it differently for a fact the Manual's "
                "authors wrote and a fact we worked out from their wording."
            ),
            blocks.callout(
                "good",
                "The trust metadata survived, and it changed an answer",
                "Upstream records, for every citation, whether it read an actual link the authors "
                "wrote (`href`) or inferred it from the wording (`regex`), and how certain that "
                "reading is. Those two facts are carried into the graph as part of the citation "
                "rather than flattened away.\n\n"
                "It paid off immediately. Asked which parts of the Manual an amendment to section 43 "
                "would affect, five Parts turn out to be in the list **entirely** on citations "
                "inferred from a bare mention of \"section 43\" — not on links anyone wrote. "
                "\"This Part needs reviewing\" is a materially weaker claim there, and without the "
                "trust metadata there would be no way to know.",
                links=[{"label": "The full report", "href": "#/reports?open=ontology"}],
            ),
            blocks.prose("### What the corpus underneath it looks like"),
            blocks.stats(
                [
                    {"label": "Manual pages", "value": corpus["pages"]},
                    {"label": "Passages", "value": corpus["chunks"]},
                    {"label": "Parts", "value": corpus["parts"]},
                    {"label": "Legislative provisions", "value": corpus["provisions"]},
                    {"label": "Numbered units", "value": corpus["units"]},
                ],
                note=f"The pinned upstream extraction, commit `{facts.pin['commit'][:12]}`. It is "
                     f"read-only here: this project consumes it and never re-derives it. The section "
                     f"43 slice of it — how many passages, how many citations — is measured by the "
                     f"generated reports, which run with the full corpus present.",
            ),
            blocks.prose(
                "### The two rules, and why nothing they produce is trusted\n\n"
                "A rule is an explicit, fixed derivation — not a model, and not something that "
                "learns. The programme requires an expert to approve every one before its output "
                "may be used. Neither of these has been approved, so the code enforces the "
                "consequence rather than trusting the file: everything they produce is written into "
                "the inferred compartment with a *candidate* label and a *requires human review* "
                "flag."
            ),
            blocks.cards(rule_cards),
            blocks.prose("### The checks that block publication"),
            blocks.table(
                (("shape", "Check"), ("file", "Where"), ("what", "What it stops")),
                _shape_rows(facts),
                note="These are {{SHACL}} constraints. Every one has a fixture built to violate it, "
                     "because an untested check that never matches anything is worse than no check: "
                     "it reads as coverage. Against the real content they report 0 defects.",
            ),
        ],
    }


def _shape_rows(facts: Facts) -> list[dict[str, Any]]:
    rows = []
    for name, graph in facts.shapes.items():
        for shape in sorted(graph.subjects(RDF.type, SH.NodeShape)):
            direct = [" ".join(str(value).split()) for value in graph.objects(shape, SH.message)]
            nested = [
                " ".join(str(value).split())
                for prop in graph.objects(shape, SH.property)
                for value in graph.objects(prop, SH.message)
            ]
            sparql = [
                " ".join(str(value).split())
                for constraint in graph.objects(shape, SH.sparql)
                for value in graph.objects(constraint, SH.message)
            ]
            texts = direct + nested + sparql
            rows.append(
                {
                    "shape": _label(graph, shape),
                    "file": f"`shapes/{name}`",
                    "what": texts[0] if texts else "—",
                    "detail": [blocks.listing(texts)] if len(texts) > 1 else [],
                }
            )
    return rows


def _questions(facts: Facts) -> dict[str, Any]:
    by_query = {query.question_id: query for query in facts.queries}
    competency = facts.gold["competency_question"]

    rows = []
    for record in competency:
        query = by_query.get(record["id"])
        detail: list[dict[str, Any]] = []
        if record.get("expected_concepts"):
            detail.append(blocks.prose("**A good answer mentions:** "
                                       + ", ".join(f"*{c}*" for c in record["expected_concepts"])))
        expected = record.get("expected_sources") or {}
        if expected.get("required"):
            detail.append(blocks.prose("**Must cite:** "
                                       + ", ".join(f"`{r}`" for r in expected["required"])))
        if expected.get("supporting"):
            detail.append(blocks.prose("**May also cite:** "
                                       + ", ".join(f"`{r}`" for r in expected["supporting"])))
        if record.get("answer_shape"):
            detail.append(blocks.prose(f"**What a good answer looks like.** {record['answer_shape']}"))
        if record.get("caveats"):
            detail.append(blocks.callout("warn", "Where an answer can go wrong", str(record["caveats"])))
        if query:
            detail.append(
                blocks.callout(
                    "note",
                    "What the stored query does not establish",
                    query.limits + "\n\nEvery stored query carries a line like this. A query that "
                    "returns a neat table always looks like an answer, and this is where it says "
                    "what it has not proved.",
                    links=[{"label": f"Read {query.path.name}",
                            "href": f"{BLOB}/queries/competency/{query.path.name}"}],
                )
            )

        if query:
            state, tone = "answerable now", "good"
        elif record.get("category") in {"search", "retrieval"}:
            state, tone = "needs a later stage", "gap"
        else:
            state, tone = "no query yet", "warn"

        rows.append(
            {
                "id": f"`{record['id']}`",
                "question": record["question"],
                "who": record.get("asked_by", "—"),
                "state": {"chips": [{"label": state, "tone": tone}]},
                "anchor": record["id"],
                "search": f"{record['id']} {record['question']} {record.get('asked_by', '')}",
                "detail": detail,
            }
        )

    return {
        "id": "questions",
        "title": "The questions it must answer",
        "lede": (
            "A {{Competency question}} is an ordinary question the finished system has to be able to "
            "answer. They are written first, by people, and everything built afterwards is measured "
            "against them. This is the list — including the ones it cannot answer, which are the "
            "more informative half."
        ),
        "blocks": [
            blocks.stats(
                [
                    {"label": "Questions on the list", "value": len(competency), "tone": "good"},
                    {"label": "Answerable from the graph today", "value": len(facts.queries), "tone": "good"},
                    {"label": "Need search or AI retrieval first", "value":
                        sum(1 for row in rows if row["state"]["chips"][0]["label"] == "needs a later stage"),
                     "note": "two stages that do not exist yet", "tone": "gap"},
                    {"label": "Answered by refusing", "value": 1,
                     "note": "CQ-0012 returns the things it must not say", "tone": "note"},
                ]
            ),
            blocks.callout(
                "note",
                "One of them is answered by saying no",
                "*Is the connotation in this trade mark strong enough to warrant a ground for "
                "rejection?* is an evaluative judgement for the decision maker. The system's answer "
                "is the list of outputs that would answer it and must never be produced. That is a "
                "designed behaviour, not a missing feature.",
                links=[{"label": "What it must never say", "href": "#/limits"}],
            ),
            blocks.table(
                (("id", "ID"), ("question", "Question"), ("who", "Asked by"), ("state", "Today")),
                rows,
                search=True,
                note="Click a row for what a good answer has to contain, and for what the stored "
                     "query does not prove.",
            ),
            blocks.prose(
                "### Two other kinds of question\n\n"
                "**Retrieval questions** test a generated answer over retrieved passages — whether "
                "it cites the right evidence and qualifies itself properly. **Search questions** "
                "test ranked results: a query, the passages that should come back, and the ones that "
                "are tempting and wrong. Both are held to the same standard and both wait on stages "
                "that have not been built."
            ),
            blocks.stats(
                [
                    {"label": "Retrieval questions", "value": facts.gold.count("gold_retrieval_question"),
                     "note": "target 20–50", "tone": _band(facts.gold.count("gold_retrieval_question"), 20, 50)},
                    {"label": "Search questions", "value": facts.gold.count("gold_search_question"),
                     "note": "target 20–50", "tone": _band(facts.gold.count("gold_search_question"), 20, 50)},
                    {"label": "Expected reasoning results", "value": facts.gold.count("reasoning_expectation"),
                     "note": "target met", "tone": "good"},
                ]
            ),
        ],
    }


def _limits(facts: Facts) -> dict[str, Any]:
    prohibited = facts.gold["prohibited_use"]
    kinds: dict[str, int] = {}
    for record in prohibited:
        kinds[str(record.get("kind", "—"))] = kinds.get(str(record.get("kind", "—")), 0) + 1

    rows = []
    for record in prohibited:
        detail = [
            blocks.callout("warn", "Why it must not be said", str(record.get("why", "—"))),
        ]
        if record.get("notes"):
            detail.append(blocks.prose(f"_{record['notes']}_"))
        detail.append(blocks.prose(
            f"**Caught by:** {record.get('detectable_by', '—')} · "
            f"**Approved by:** {record.get('approved_by', '—')} on {record.get('approved_date', '—')}"
        ))
        rows.append(
            {
                "quote": f"“{record['prohibited']}”",
                "kind": {"chips": [{"label": str(record.get("kind", "—")).replace("_", " "), "tone": "warn"}]},
                "search": f"{record['id']} {record['prohibited']} {record.get('kind','')}",
                "detail": detail,
            }
        )

    return {
        "id": "limits",
        "title": "What it cannot do",
        "lede": (
            "The honest half of the demonstration. Every gap on this page is counted by the same "
            "run that produces the successes, and every prohibition was written and signed by a "
            "person as a thing the system must never say."
        ),
        "blocks": [
            blocks.prose(
                "### Things it must never say\n\n"
                "A {{Prohibited use / prohibited inference}} is a conclusion the system is not "
                "allowed to produce, recorded as explicitly as the right answers and tested just as "
                "hard. They are not warnings on an interface — three of them are enforced by code, "
                "and one has become a constraint that blocks publication outright."
            ),
            blocks.bars(
                [{"label": kind.replace("_", " "), "value": count, "note": f"{count} recorded"}
                 for kind, count in sorted(kinds.items(), key=lambda item: -item[1])],
                note="Six kinds were specified; five are represented. The missing one is "
                     "*stale source* — all three of its draft records are held behind decisions "
                     "nobody has made yet.",
            ),
            blocks.table(
                (("quote", "The system must not say"), ("kind", "Kind")),
                rows,
                search=True,
            ),
            blocks.prose("### Gaps in the model, counted"),
            blocks.cards(
                [
                    {
                        "title": "The taxonomy is empty",
                        "subtitle": "the largest single gap",
                        "text": "*Ground of refusal*, *legal test*, *relevant factor* and *exception* "
                                "are declared and hold nothing. All 52 legal ideas sit as a bare "
                                "concept, because the record has no field for the kind and deciding "
                                "which one applies is a legal judgement.",
                        "badges": [{"label": "needs one pass by one person", "tone": "gap"}],
                        "links": [{"label": "Question 1 in your queue", "href": "#/inbox"}],
                    },
                    {
                        "title": "No idea has a definition",
                        "subtitle": "by design, not by omission",
                        "text": "The records carry the passages a meaning is drawn from and no "
                                "definition text. Writing one would be authoring legal content. The "
                                "absence is reported and counted rather than filled with something "
                                "plausible.",
                        "badges": [{"label": "expert-owned", "tone": "note"}],
                    },
                    {
                        "title": "Most of the vocabulary is flat",
                        "subtitle": "39 of 52 ideas",
                        "text": "No broader term, no narrower term. The hierarchy is where a search "
                                "system gets its ability to generalise, so a mostly-flat vocabulary "
                                "is a list with extra steps.",
                        "badges": [{"label": "measured", "tone": "gap"}],
                    },
                    {
                        "title": "Point-in-time questions are unanswerable",
                        "subtitle": "and will stay that way",
                        "text": "There is no version stamp across the corpus; the amendment history "
                                "is the upstream repository's own history. *What did the practice say "
                                "in 2019* is out of reach under this approach, and the question that "
                                "asks it carries that limitation on its face.",
                        "badges": [{"label": "structural", "tone": "warn"}],
                    },
                    {
                        "title": "No court decision text exists anywhere",
                        "subtitle": "58 decisions cited, none held",
                        "text": "*Which cases interpret this test* is answerable. *What did the court "
                                "hold* is not, and one of the prohibitions exists to stop the system "
                                "pretending otherwise.",
                        "badges": [{"label": "a scope decision", "tone": "note"}],
                        "links": [{"label": "It is question 9 in your queue", "href": "#/inbox"}],
                    },
                    {
                        "title": "Six predicates have been used once each",
                        "subtitle": "out of fourteen",
                        "text": "A relationship term seen a single time is a term whose boundaries "
                                "nobody has tested. One reviewer's own note says a predicate \"reads "
                                "plausibly and says the wrong thing\" on the record that uses it — "
                                "and it was left in as an example rather than quietly fixed.",
                        "badges": [{"label": "measured", "tone": "warn"}],
                    },
                ]
            ),
            blocks.callout(
                "note",
                "Read the generated report for the full list",
                "Section 5 of the ontology report is produced by the same run that builds the graph, "
                "so it cannot drift out of date the way a hand-written page can.",
                links=[{"label": "Open the report", "href": "#/reports?open=ontology"}],
            ),
        ],
    }


def _decisions(facts: Facts) -> dict[str, Any]:
    provisional = [adr for adr in facts.adrs if adr.authority == "agent-proposed"
                   and "provisional" in adr.status.lower()]
    counts: dict[str, int] = {}
    for adr in facts.adrs:
        counts[adr.authority] = counts.get(adr.authority, 0) + 1

    tone_for = {"human": "good", "inherited": "note", "derived": "note", "agent-proposed": "warn"}
    rows = [
        {
            "id": f"`{adr.identifier}`",
            "title": adr.title,
            "authority": {"chips": [{"label": adr.authority, "tone": tone_for.get(adr.authority, "muted")}]},
            "date": adr.date,
            "search": f"{adr.identifier} {adr.title} {adr.authority} {adr.status}",
            "detail": [
                blocks.prose(f"**Status.** {adr.status}"),
                blocks.prose(adr.summary),
                blocks.prose(f"[Read it in full]({BLOB}/docs/DECISIONS.md#"
                             f"{_anchor(adr.identifier, adr.title)})"),
            ],
        }
        for adr in reversed(facts.adrs)
    ]

    return {
        "id": "decisions",
        "title": "Every decision on the record",
        "lede": (
            f"{len(facts.adrs)} decisions, each with a date and — the part that matters — a stated "
            "**authority**: who was entitled to make it. The log is append-only. A decision is never "
            "edited or deleted; it is superseded by a new one that says so."
        ),
        "blocks": [
            blocks.stats(
                [
                    {"label": "Decisions recorded", "value": len(facts.adrs)},
                    {"label": "Made by you", "value": counts.get("human", 0), "tone": "good",
                     "note": "yours, and not overturnable by an agent"},
                    {"label": "Forced by the evidence", "value": counts.get("derived", 0), "note": "defensible without a human"},
                    {"label": "Inherited from the roadmap", "value": counts.get("inherited", 0)},
                    {"label": "An agent's call, still provisional", "value": len(provisional),
                     "tone": "warn", "note": "waiting on you to confirm or overturn"},
                ]
            ),
            blocks.callout(
                "warn",
                f"{len(provisional)} decisions are marked provisional",
                "They were made by an agent so that work could continue rather than stop. Provisional "
                "means a person has not looked at them. Two questions in your queue put them to you "
                "in batches, in plain language, with a tick box each.",
                links=[{"label": "Go to your decisions", "href": "#/inbox"}],
            ),
            blocks.table(
                (("id", "ID"), ("title", "Decision"), ("authority", "Made by"), ("date", "Date")),
                rows,
                search=True,
                note="Newest first. Click a row for the context and a link to the full entry.",
            ),
        ],
    }


def _anchor(identifier: str, title: str) -> str:
    text = f"{identifier} — {title}".lower()
    text = re.sub(r"[^\w\s-]", "", text.replace("—", " "))
    return re.sub(r"\s+", "-", text.strip())


def _reports(facts: Facts) -> dict[str, Any]:
    present = [entry for entry in REPORTS if (REPORTS_DIR / entry[0]).exists()]
    return {
        "id": "reports",
        "title": "The generated reports",
        "lede": (
            f"{len(present)} reports, none of them hand-written. Each is produced by a command "
            "that reads the data and counts, so it cannot say something the data does not "
            "support and cannot go stale while the data moves. They are rendered here in full."
        ),
        "blocks": [
            blocks.callout(
                "note",
                "Why these are not summarised on this site",
                "A summary is a second version with its own life. These are the originals: the "
                "dashboard renders them and restates nothing from them.",
            ),
            *[blocks.report(f"reports/{name}", title, lede=lede) for name, title, lede in present],
        ],
    }


def _inbox(facts: Facts) -> dict[str, Any]:
    """The form's data. Rendered by `site/inbox.js`, not by the block renderer."""
    question_set = facts.questions
    answered: dict[str, list[dict[str, Any]]] = {}
    for ruling in facts.rulings:
        for answer in ruling.answers:
            identifier = str(answer.get("id"))
            answered.setdefault(identifier, []).append(
                {
                    "value": answer.get("value"),
                    "label": answer.get("label"),
                    "notes": answer.get("notes"),
                    "received": ruling.received,
                    "issue": ruling.origin,
                    "applied": bool(ruling.applied),
                }
            )

    return {
        "id": "inbox",
        "title": "Your decisions",
        "lede": (
            "Everything currently waiting on a person. Each item says what is going on, why only "
            "you can settle it, and what stays stuck until you do. Answer as many or as few as you "
            "like — a partial answer is useful and nothing is lost between visits."
        ),
        "updated": question_set.updated,
        "repo": REPO_URL,
        "themes": [dict(theme) for theme in question_set.themes],
        "questions": [dict(question.raw) for question in question_set.questions],
        "answered": answered,
        "rulings": [
            {
                "file": ruling.path.name,
                "received": ruling.received,
                "issue": ruling.issue,
                "origin": ruling.origin,
                "origin_kind": ruling.origin_kind,
                "count": len(ruling.answers),
                "applied": ruling.applied,
            }
            for ruling in facts.rulings
        ],
    }


def _site(facts: Facts, generated: str) -> dict[str, Any]:
    return {
        "generated": generated,
        "repo": REPO_URL,
        "pin": {
            "commit": facts.pin["commit"],
            "short": facts.pin["commit"][:12],
            "repo": facts.pin["repo"],
            "manual_version": facts.pin["manual_extractor_version"],
            "legislation_version": facts.pin["legislation_extractor_version"],
        },
        "waiting": len(facts.questions.asked),
        "nav": [{"id": page, "label": label, "blurb": blurb} for page, label, blurb in PAGES],
    }


# --------------------------------------------------------------------- build


def _markers(value: Any) -> set[str]:
    if isinstance(value, str):
        return set(_MARKER.findall(value))
    if isinstance(value, dict):
        return set().union(*(_markers(item) for item in value.values())) if value else set()
    if isinstance(value, list):
        return set().union(*(_markers(item) for item in value)) if value else set()
    return set()


def check_glossary(pages: dict[str, Any], glossary: dict[str, dict[str, str]]) -> None:
    """A `{{term}}` marker naming a term the glossary does not hold is an error.

    The alternative is a tooltip that silently does not appear, which is how an
    explanation aimed at a reader who needs it quietly stops being offered.
    """
    used = set().union(*(_markers(page) for page in pages.values())) if pages else set()
    missing = sorted(term for term in used if term not in glossary)
    if missing:
        raise BuildError(
            "these glossary markers name terms `docs/GLOSSARY.md` does not define: "
            + ", ".join(missing)
            + ". Add the term there — one glossary, two readers — or drop the marker."
        )


def build(*, generated: str | None = None) -> dict[str, Any]:
    """Every page, keyed by output filename."""
    facts = gather()
    stamp = generated or date.today().isoformat()
    pages = {
        "overview.json": _overview(facts),
        "vocabulary.json": _vocabulary(facts),
        "ontology.json": _ontology(facts),
        "graph.json": _graph_page(facts),
        "questions.json": _questions(facts),
        "limits.json": _limits(facts),
        "decisions.json": _decisions(facts),
        "reports.json": _reports(facts),
        "inbox.json": _inbox(facts),
    }
    check_glossary(pages, facts.glossary)
    pages["glossary.json"] = {"terms": facts.glossary}
    pages["site.json"] = _site(facts, stamp)
    return pages


def _serialise(payload: Any) -> str:
    return json.dumps(payload, indent=1, ensure_ascii=False, sort_keys=False) + "\n"


def write(pages: dict[str, Any] | None = None, out_dir: Path | None = None) -> list[Path]:
    """Write the JSON, and copy the generated reports in beside it."""
    pages = pages if pages is not None else build()
    out_dir = out_dir or DATA_DIR
    out_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for name, payload in pages.items():
        path = out_dir / name
        path.write_text(_serialise(payload), encoding="utf-8")
        written.append(path)

    reports_out = out_dir / "reports"
    reports_out.mkdir(exist_ok=True)
    for name, _, _ in REPORTS:
        source = REPORTS_DIR / name
        if source.exists():
            shutil.copyfile(source, reports_out / name)
            written.append(reports_out / name)
    return written


def check(out_dir: Path | None = None) -> list[str]:
    """Lines describing how the committed data differs from a regeneration.

    The generated-on stamp is excluded — it is the one field that legitimately
    changes without the content changing. Everything else drifting means the
    site is showing a number the repository no longer holds.
    """
    out_dir = out_dir or DATA_DIR
    fresh = build()
    stale: list[str] = []
    for name, payload in fresh.items():
        path = out_dir / name
        if not path.exists():
            stale.append(f"{name}: not generated yet")
            continue
        committed = json.loads(path.read_text(encoding="utf-8"))
        if name == "site.json":
            committed = dict(committed)
            payload = dict(payload)
            committed.pop("generated", None)
            payload.pop("generated", None)
        if committed != payload:
            stale.append(f"{name}: differs from a regeneration")
    return stale
