"""The review pack for RULE-0001 — the passages it flags, in full.

The owner was asked to approve or reject RULE-0001 and answered *"Show me the 71
flagged passages first"* (OQ-0003, issue #12). This generates what he asked to
see, and corrects the question while it does: **the rule flags five passages, not
seventy-one.** 71 was the size of the graph the rule builds, and S011 wrote it
into the question as a count of flags (Q-41).

So the pack is short, and being short is the finding. Five passages out of 216
is a rule that is selective; 71 out of 216 would have been a rule worth
distrusting. He can read all five in a couple of minutes and rule on evidence
rather than on a summary.

Generated, never hand-written, for ADR-0042's reason: a hand-copied passage is
a passage that drifts from the snapshot, and the whole claim this pack makes is
"here is what the Manual actually says".
"""

from __future__ import annotations

from datetime import date
from pathlib import Path

from tm_knowledge.config import REPO_ROOT
from tm_knowledge.ontology import rules as rules_module
from tm_knowledge.ontology.build import build
from tm_knowledge.ontology.namespaces import TMK
from tm_knowledge.stage0 import goldset
from tm_knowledge.upstream.loader import load_corpus

__all__ = ["FLAGS_PATH", "RULE_ID", "flagged_refs", "render", "write"]

FLAGS_PATH = REPO_ROOT / "data" / "derived" / "reports" / "rule-0001-flags.md"
RULE_ID = "RULE-0001"

_REF_PREFIX = "https://data.ipaustralia.gov.au/tmk/ref/"


def _ref_of(node) -> str:
    """The `chunk_ref` behind a ref IRI. `%23` is `#` — never a prefixed name (Q-32)."""
    return str(node).removeprefix(_REF_PREFIX).replace("%23", "#")


def flagged_refs(dataset=None) -> tuple[str, ...]:
    """Every passage RULE-0001 flags, as `chunk_ref`s, in corpus order."""
    if dataset is None:
        dataset, _ = build()
    rule = {r.rule_id: r for r in rules_module.load_rules()}[RULE_ID]
    produced = rule.construct(dataset)
    return tuple(sorted(_ref_of(node) for node in produced.subjects(TMK.mixedAuthority, None)))


def render(generated: str | None = None) -> str:
    corpus = load_corpus()
    gold = goldset.load()
    dataset, _ = build()
    rule = {r.rule_id: r for r in rules_module.load_rules()}[RULE_ID]
    produced = rule.construct(dataset)
    refs = tuple(sorted(_ref_of(node) for node in produced.subjects(TMK.mixedAuthority, None)))
    triples = len(produced)

    # The expert's own typing is what the rule reads. Grouped per passage so the
    # pack can show *why* each one fired, rather than asserting that it did.
    by_ref: dict[str, dict[str, list[dict]]] = {}
    for record in gold["gold_entity"]:
        if record["source_ref"] in refs:
            bucket = by_ref.setdefault(record["source_ref"], {"law": [], "practice": []})
            if record["type"] == "LegislativeProvision":
                bucket["law"].append(record)
            elif record["type"] == "ManualInstruction":
                bucket["practice"].append(record)

    stamp = generated or date.today().isoformat()
    parts: list[str] = [
        "<!-- Generated by tm_knowledge.ontology.flags. Do not hand-edit. -->",
        "",
        "# RULE-0001 — every passage it flags, in full",
        "",
        f"**Generated {stamp}** by `tmk-flags --write`, from the pinned snapshot and "
        "`eval/gold/entities.yaml`.",
        "",
        "## Why you are reading this",
        "",
        "You were asked to approve or reject RULE-0001 and answered *“Show me the 71 "
        "flagged passages first”* (OQ-0003). Here they are — and the first thing to say "
        "is that the question gave you a wrong number.",
        "",
        f"**The rule flags {len(refs)} passages, not 71.** Seventy-one was the number of rows "
        "of data the rule writes, and each flag carries roughly fourteen rows of "
        "record-keeping with it — which rule produced it, what it read, whether anyone has "
        "approved it. Someone read the row count off a generated table and wrote it into your "
        f"question as a count of flagged passages. It is {len(refs)}, out of the 216 passages "
        "in scope.",
        "",
        "That correction is worth more than the number. **A rule that fires on 5 passages in "
        "216 is being selective; one that fired on 71 would barely be narrowing anything.** "
        "You were being asked to judge a much blunter instrument than the one that exists.",
        "",
        "## What the rule claims, in one sentence",
        "",
        "*This passage contains both words quoted from the Act and IP Australia's own "
        "practice guidance, so anything drawn from it must keep the two apart.*",
        "",
        "It is not reading the text to decide that. It fires where **a trade marks expert "
        "has already typed one phrase in the passage as legislation and another as practice** "
        "— the approved records in `eval/gold/entities.yaml`, each signed and dated. The "
        "rule joins two human judgements; it makes none.",
        "",
        "## What it cannot do, and you should hold it to this",
        "",
        rule.limits,
        "",
        "## The evidence",
        "",
        f"{len(refs)} passages, in order. For each: what the Manual says, and the phrases the "
        "expert typed that made the rule fire.",
        "",
    ]

    for index, ref in enumerate(refs, start=1):
        chunk = corpus.chunks.get(ref)
        mentions = by_ref.get(ref, {"law": [], "practice": []})
        parts.append(f"### {index}. `{ref}`")
        parts.append("")
        if chunk is None:
            parts.append(
                "**This passage is not in the pinned snapshot.** That is a defect, not a "
                "finding — the flag rests on a gold record pointing at a passage the "
                "corpus does not hold."
            )
            parts.append("")
            continue
        parts.append(f"*{' › '.join(chunk.heading_path) or 'no heading path'}* — "
                     f"page `{chunk.page_ref}`, position {chunk.ordinal}")
        parts.append("")
        parts.append("> " + chunk.text.replace("\n", "\n> "))
        parts.append("")
        parts.append("| the expert read this as | the words | record |")
        parts.append("|---|---|---|")
        for record in sorted(mentions["law"], key=lambda r: r["id"]):
            resolves = f" → `{record['resolves_to']}`" if record.get("resolves_to") else ""
            parts.append(
                f"| quoted legislation | “{record['surface']}”{resolves} | "
                f"`{record['id']}`, signed {record.get('approved_by') or '—'} "
                f"{record.get('approved_date') or ''} |"
            )
        for record in sorted(mentions["practice"], key=lambda r: r["id"]):
            parts.append(
                f"| the Registrar's practice | “{record['surface']}” | "
                f"`{record['id']}`, signed {record.get('approved_by') or '—'} "
                f"{record.get('approved_date') or ''} |"
            )
        parts.append("")
        if chunk.provisions:
            cited = sorted({edge.id for edge in chunk.provisions})
            parts.append(f"Provisions this passage cites: {', '.join(f'`{c}`' for c in cited)}")
            parts.append("")

    parts.extend(
        [
            "## What approving it would mean",
            "",
            "Today every one of these flags is stored as *candidate — needs a human*, so "
            "nothing may be built on it. Approving the rule means a later feature may say "
            "“this passage mixes law and practice” and be relied on when it does.",
            "",
            "Approving it does **not** approve the five passages, or the expert's typing "
            "underneath them — those are already signed. It approves the join: that two "
            "such phrases in one passage is worth flagging.",
            "",
            "Rejecting it deletes the rule. The five passages stay exactly as they are; only "
            "the derived flag goes.",
            "",
            f"The re-ask is **OQ-0019** on the dashboard. Until you answer it, the rule stays "
            f"`PENDING` and its {triples} rows stay quarantined.",
            "",
        ]
    )
    return "\n".join(parts).rstrip() + "\n"


def write(path: Path | None = None, generated: str | None = None) -> Path:
    path = path or FLAGS_PATH
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render(generated), encoding="utf-8")
    return path
