"""Generate `ontology/draft/relations.ttl` from the relation dictionary.

Until 2026-10-08 the closed predicate list was derived from the approved register
alone: every term was one an expert had used, and the file carried a label and a
usage count but no definition. The ontology review found the cost of that (Q-73):
the relate prompt's only definition of a predicate was the first signed record that
used it, and two of those records were recorded the wrong way round. The owner
approved defining the predicates (review D1) and a small authority vocabulary (C3)
on 2026-10-08 (ADR-0121, ADR-0123).

So the dictionary is now `ontology/predicates.py` — a definition, a reading, an
example and a counter-example per predicate, each machine-written and unreviewed —
and this module renders it. It still counts usage, and it counts the two stores
apart and never sums them (ADR-0080 c3):

- `tmk:ApprovedRelation` — a predicate a signed record uses. `tmk:usageCount` and
  `tmk:usedBy` are the signed records, as before.
- `tmk:AdmittedRelation` — a predicate the owner admitted that no signed record
  uses yet. On the closed list all the same.

`tmk:authoredUsageCount` is the machine-written records' count. The SKOS relation
`broader` is SKOS's own term and is not redeclared here; `related` is retired as a
relationship (ADR-0131).

Each predicate also carries the kinds it joins — `tmk:expectedSubjectKind`,
`tmk:expectedObjectKind` — annotations that infer nothing, which the harness checks
machine-written edges against (ADR-0131). They are the ontology's top level as links.

What the generator still refuses to do: assert a narrow `rdfs:domain` or
`rdfs:range` from observed usage. Under OWL 2 RL a domain assertion reclassifies
every subject of the property; the observed types are annotations, and the asserted
domain and range are `tmk:LegalMatter`, which licenses nothing false.

Run: `tmk-ontology-relations --write`. A test asserts the committed file is exactly
what a regeneration produces, so the two cannot drift.
"""

from __future__ import annotations

import re
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path

from tm_knowledge.authored import store as authored_store
from tm_knowledge.config import REPO_ROOT
from tm_knowledge.ontology.predicates import END_KINDS, KIND_CLASS, PREDICATES, RETIRED, SKOS_PREDICATES, Predicate
from tm_knowledge.stage0 import goldset

__all__ = ["RELATIONS_PATH", "PredicateUsage", "collect", "render", "write", "observed_type"]

RELATIONS_PATH = REPO_ROOT / "ontology" / "draft" / "relations.ttl"

_HEADER = """\
@prefix tmk:     <https://data.ipaustralia.gov.au/tmk/ns/> .
@prefix tmkc:    <https://data.ipaustralia.gov.au/tmk/concept/> .
@prefix owl:     <http://www.w3.org/2002/07/owl#> .
@prefix rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs:    <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd:     <http://www.w3.org/2001/XMLSchema#> .
@prefix skos:    <http://www.w3.org/2004/02/skos/core#> .
@prefix prov:    <http://www.w3.org/ns/prov#> .
@prefix dcterms: <http://purl.org/dc/terms/> .

# GENERATED by tm_knowledge.ontology.relations from tm_knowledge.ontology.predicates,
# with usage counted from eval/gold/ and authored/ apart.
# Do not hand-edit: a test compares this file against a regeneration.
# To change a predicate, change the dictionary; to add one, the owner admits it.

<https://data.ipaustralia.gov.au/tmk/ns/relations>
    a owl:Ontology ;
    rdfs:label "TM-Knowledge — relation dictionary"@en-AU ;
    rdfs:comment \"\"\"The closed list of predicates a relationship may use, each defined.

{terms} predicates besides SKOS broader: {approved} used by the
{signed} signed relationships in `eval/gold/relationships.yaml`, of which
{singletons} are used exactly once, and {admitted} admitted by the owner (on
2026-10-08 and 2026-10-09) and used by no signed record yet. Machine-written
relationships use {authored_terms} of them, {authored} times — counted apart, never
added in. skos:related is retired as a relationship (ADR-0131).

Every definition, reading, example and counter-example here was written by an
agent and is unreviewed (ADR-0121, ADR-0123). A record whose triple does not read
the way its predicate's tmk:reading says is a defect in the record.

Domain and range are `tmk:LegalMatter` throughout. The narrow types each
predicate has actually been seen with are annotations and infer nothing; see
tmk:LegalMatter in the legal-concepts module for why. The kinds each predicate may
join (tmk:expectedSubjectKind, tmk:expectedObjectKind) are annotations too: what
says how the ontology's kinds fit together, checked by the harness, not inferred.\"\"\"@en-AU ;
    owl:imports <https://data.ipaustralia.gov.au/tmk/ns/legal-concepts> ;
    owl:versionInfo "draft — generated, not approved" .
"""

#: `GC-0001` -> Concept, `TMM/...` -> ManualChunk, and so on. Structural only:
#: it reads the id or ref grammar and makes no claim about what the thing means.
#: A case is a `tmk:Decision` here, not a judicial one: whether a tribunal or the
#: Registrar's own delegate decided it is the decision module's call (review C7).
_TYPE_PATTERNS: tuple[tuple[str, str], ...] = (
    (r"^GC-[0-9]+$", "tmk:LegalConcept"),
    (r"^TMM/", "tmk:Chunk"),
    (r"^CASE/", "tmk:Decision"),
    (r"^(TMA|TMR)[0-9]{4}/", "tmk:LegislativeProvision"),
)


def observed_type(value: str) -> str:
    for pattern, term in _TYPE_PATTERNS:
        if re.match(pattern, value):
            return term
    return "tmk:LegalMatter"


def _label(predicate: str) -> str:
    """`mayGiveRiseTo` -> `may give rise to`. Mechanical, so it cannot editorialise."""
    return re.sub(r"(?<!^)(?=[A-Z])", " ", predicate).lower()


def _literal(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"@en-AU'


@dataclass(frozen=True)
class PredicateUsage:
    """One predicate: its dictionary entry and the records of each store using it."""

    predicate: str
    record_ids: tuple[str, ...]  # signed
    authored_ids: tuple[str, ...]
    subject_types: tuple[str, ...]
    object_types: tuple[str, ...]
    entry: Predicate | None = None

    @property
    def count(self) -> int:
        return len(self.record_ids)

    @property
    def authored_count(self) -> int:
        return len(self.authored_ids)


def collect(
    gold: goldset.GoldSet | None = None, authored: authored_store.AuthoredSet | None = None
) -> tuple[PredicateUsage, ...]:
    """Every predicate in the dictionary, with its usage in each store. Sorted, so
    the generated file is byte-stable across runs. A predicate a record uses that
    the dictionary lacks is still listed — without a definition — so the file says
    so rather than hiding it; the harness reports the record."""
    gold = gold or goldset.load()
    authored = authored if authored is not None else authored_store.load()
    signed: dict[str, list[dict]] = defaultdict(list)
    machine: dict[str, list[dict]] = defaultdict(list)
    for record in gold["gold_relationship"]:
        signed[str(record["predicate"])].append(record)
    for record in authored["gold_relationship"]:
        machine[str(record["predicate"])].append(record)

    names = (set(PREDICATES) | set(signed) | set(machine)) - set(SKOS_PREDICATES) - set(RETIRED)
    usages = []
    for predicate in sorted(names):
        rows = sorted(signed.get(predicate, []), key=lambda r: r["id"])
        theirs = sorted(machine.get(predicate, []), key=lambda r: r["id"])
        everything = rows + theirs
        usages.append(
            PredicateUsage(
                predicate=predicate,
                record_ids=tuple(r["id"] for r in rows),
                authored_ids=tuple(r["id"] for r in theirs),
                subject_types=tuple(sorted({observed_type(str(r["subject"])) for r in everything})),
                object_types=tuple(sorted({observed_type(str(r["object"])) for r in everything})),
                entry=PREDICATES.get(predicate),
            )
        )
    return tuple(usages)


def render(usages: tuple[PredicateUsage, ...]) -> str:
    approved = [u for u in usages if u.count]
    out = [_HEADER.format(
        terms=len(usages), approved=len(approved), signed=sum(u.count for u in usages),
        singletons=sum(1 for u in approved if u.count == 1),
        admitted=sum(1 for u in usages if not u.count and u.entry is not None),
        authored_terms=sum(1 for u in usages if u.authored_count),
        authored=sum(u.authored_count for u in usages),
    )]

    for usage in usages:
        entry = usage.entry
        kind = "tmk:ApprovedRelation" if usage.count else "tmk:AdmittedRelation"
        lines = [
            f"\ntmk:{usage.predicate} a owl:ObjectProperty ;",
            f"    a {kind} ;",
            f'    rdfs:label "{_label(usage.predicate)}"@en-AU ;',
            "    rdfs:domain tmk:LegalMatter ;",
            "    rdfs:range tmk:LegalMatter ;",
        ]
        if entry is not None:
            lines += [
                f"    skos:definition {_literal(entry.definition)} ;",
                f"    tmk:reading {_literal(entry.reading)} ;",
                f"    skos:example {_literal(entry.example)} ;",
                f"    tmk:counterExample {_literal(entry.counter_example)} ;",
                f'    tmk:admittedBy "{entry.admitted}" ;',
            ]
            if entry.authority:
                lines.append(f'    tmk:predicateAuthority "{entry.authority}" ;')
            if set(entry.subjects) != set(END_KINDS):
                lines += [f"    tmk:expectedSubjectKind {KIND_CLASS[k]} ;" for k in entry.subjects]
            if set(entry.objects) != set(END_KINDS):
                lines += [f"    tmk:expectedObjectKind {KIND_CLASS[k]} ;" for k in entry.objects]
        lines += [
            f"    tmk:usageCount {usage.count} ;",
            f"    tmk:authoredUsageCount {usage.authored_count} ;",
        ]
        for term in usage.subject_types:
            lines.append(f"    tmk:observedSubjectType {term} ;")
        for term in usage.object_types:
            lines.append(f"    tmk:observedObjectType {term} ;")
        for record_id in usage.record_ids:
            lines.append(f'    tmk:usedBy "{record_id}" ;')
        if entry is None:
            note = "Not in the relation dictionary: a record uses a predicate nobody has defined."
        elif usage.count:
            note = (f"Signed usage: {usage.count} relationship{'' if usage.count == 1 else 's'} "
                    f"({', '.join(usage.record_ids)}).")
        else:
            note = f"Admitted by the owner's ruling ({entry.admitted}); no signed record uses it yet."
        note += f" Machine-written usage: {usage.authored_count}, unreviewed."
        lines.append(f"    rdfs:comment {_literal(note)} .")
        out.append("\n".join(lines))
    return "\n".join(out) + "\n"


def write(
    path: Path | None = None, *, gold: goldset.GoldSet | None = None,
    authored: authored_store.AuthoredSet | None = None,
) -> Path:
    path = path or RELATIONS_PATH
    path.write_text(render(collect(gold, authored)), encoding="utf-8")
    return path
