"""Generate `ontology/draft/relations.ttl` from the relationship registers.

The closed predicate list is **derived, never authored by hand**. Every term in
it is one that some record in this project actually uses, and the file records
how many use it, which ones, and — since ADR-0109 — **whether a person signed
any of them**.

## Why it reads two stores now

Until today this generator read `eval/gold/relationships.yaml` and nothing else.
That was right while CLAUDE.md rule 1 forbade an agent to author a relationship
at all: the only relationships in the project were signed ones, so the only
predicates were approved ones.

It also made the dictionary a **section 43 dictionary**, and left it one for
four days after ADR-0081 withdrew the boundary. All 37 source refs in the
signed set point at `TMM/Part29`. The 14 terms are the terms one Part of 54
happened to need, and nothing in them can say that a term is *defined by* a
provision, that an act is *performed by* an office, or that a step *must occur
within* a period — which is most of what the other 53 Parts are about.

So the generator reads both stores and keeps them apart in the output:

- `tmk:ApprovedRelation` — an expert used this predicate in a signed record.
  Unchanged meaning, unchanged membership. The 14 are still the 14.
- `tmk:AuthoredRelation` — a machine used it and no expert has read a single
  record that does. New class, and the reason it is a class rather than a flag
  is ADR-0007's: a flag can be dropped by a careless projection.

A predicate used by both stores gets both types, and its counts are reported
separately. **They are never added.** A single "usage count" spanning the two
would answer *how much of this has a person looked at* in the one direction
that matters, silently (ADR-0080 consequence 3).

## What the generator still refuses to do

It does not assert a narrow `rdfs:domain` or `rdfs:range` from observed usage.
Under OWL 2 RL a domain assertion reclassifies every subject of the property,
so inferring `rdfs:domain tmk:LegalConcept` from three examples would
manufacture classifications from a sample size. The observed types are
annotations; the asserted domain and range are `tmk:LegalMatter`, which
licenses nothing false.

Run: `tmk-ontology-relations --write`. A test asserts the committed file is
exactly what a regeneration produces, so the two cannot drift.
"""

from __future__ import annotations

import re
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path

from tm_knowledge.config import REPO_ROOT
from tm_knowledge.authored import store as authored_store
from tm_knowledge.stage0 import goldset

__all__ = ["RELATIONS_PATH", "PredicateUsage", "collect", "render", "write"]

RELATIONS_PATH = REPO_ROOT / "ontology" / "draft" / "relations.ttl"

_HEADER = """\
@prefix tmk:     <https://data.ipaustralia.gov.au/tmk/ns/> .
@prefix tmkc:    <https://data.ipaustralia.gov.au/tmk/concept/> .
@prefix owl:     <http://www.w3.org/2002/07/owl#> .
@prefix rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs:    <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd:     <http://www.w3.org/2001/XMLSchema#> .
@prefix skos:    <http://www.w3.org/2004/02/skos/core#> .
@prefix prov:    <http://www.w3.org/ns/prov#> .
@prefix dcterms: <http://purl.org/dc/terms/> .

# GENERATED by tm_knowledge.ontology.relations from eval/gold/relationships.yaml
# AND authored/relationships.yaml. Do not hand-edit: a test compares this file
# against a regeneration.
#
# To add an APPROVED predicate, have an expert approve a relationship that uses
# it. An authored predicate arrives the way any authored content does — a
# record with an envelope, stamped unreviewed (ADR-0079, ADR-0109).

<https://data.ipaustralia.gov.au/tmk/ns/relations>
    a owl:Ontology ;
    rdfs:label "TM-Knowledge — relation dictionary"@en-AU ;
    rdfs:comment \"\"\"The closed list of predicates extraction may propose, in two halves that
are never added together.

**{approved_terms} approved terms**, from the {approved_count} relationships in
`eval/gold/relationships.yaml` that a named expert signed. {approved_singletons} of them are
used exactly once, and that number is the one to read before treating this half
as settled — a term seen once is a term whose boundaries nobody has tested.
Every one of those 37 source refs points at `TMM/Part29`, so this half of the
dictionary is what section 43 needed and nothing else.

**{authored_terms} authored terms**, from the {authored_count} relationships in
`authored/relationships.yaml` that a machine wrote across the whole Manual and
both instruments. **No expert has read any of them.** {new_terms} of the {authored_terms}
appear in no signed record at all and exist only because the corpus outside
Part 29 states relations the approved half cannot express.

A predicate carries `tmk:ApprovedRelation`, `tmk:AuthoredRelation`, or both.
Reading the class rather than the presence of the term is the difference
between a dictionary an expert built and one a model did (ADR-0109).

Domain and range are `tmk:LegalMatter` throughout. The narrow types each
predicate has actually been seen with are annotations and infer nothing; see
tmk:LegalMatter in the legal-concepts module for why.\"\"\"@en-AU ;
    owl:imports <https://data.ipaustralia.gov.au/tmk/ns/legal-concepts> ;
    owl:versionInfo "draft — generated, not approved" .
"""

#: `GC-0001` -> Concept, `TMM/...` -> ManualChunk, and so on. Structural only:
#: it reads the id or ref grammar and makes no claim about what the thing means.
_TYPE_PATTERNS: tuple[tuple[str, str], ...] = (
    (r"^GC-[0-9]+$", "tmk:LegalConcept"),
    (r"^TMM/", "tmk:Chunk"),
    (r"^CASE/", "tmk:JudicialDecision"),
    (r"^(TMA|TMR)[0-9]{4}/", "tmk:LegislativeProvision"),
)


def observed_type(value: str) -> str:
    for pattern, term in _TYPE_PATTERNS:
        if re.match(pattern, value):
            return term
    return "tmk:LegalMatter"


def _label(predicate: str) -> str:
    """`mayGiveRiseTo` -> `may give rise to`. Mechanical, so it cannot editorialise."""
    return re.sub(r"(?<!^)(?=[A-Z])", " ", predicate).lower()


#: How many authored record ids a predicate lists before the list is truncated.
#: `tmk:usedBy` exists to be the route from a term back to the sentences that
#: put it there, and 85 of them on one predicate is not a route, it is a wall.
#: The approved half is never truncated — it is small and every id in it was
#: signed by somebody.
AUTHORED_USED_BY_LIMIT = 12


@dataclass(frozen=True)
class PredicateUsage:
    """One predicate, and every record in either store that uses it.

    The two stores are separate fields and there is deliberately no property
    that sums them. A caller wanting a total has to write the addition itself,
    which is the point: it then has to decide what the total means.
    """

    predicate: str
    approved_ids: tuple[str, ...]
    authored_ids: tuple[str, ...]
    subject_types: tuple[str, ...]
    object_types: tuple[str, ...]

    @property
    def approved_count(self) -> int:
        return len(self.approved_ids)

    @property
    def authored_count(self) -> int:
        return len(self.authored_ids)

    @property
    def is_approved(self) -> bool:
        """An expert used this term in a record they signed."""
        return bool(self.approved_ids)

    @property
    def is_authored(self) -> bool:
        """A machine used it, in a record nobody has read."""
        return bool(self.authored_ids)


def collect(
    gold: goldset.GoldSet | None = None,
    authored: authored_store.AuthoredSet | None = None,
) -> tuple[PredicateUsage, ...]:
    """Every predicate in either store, with its usage. Sorted, so the
    generated file is byte-stable across runs."""
    gold = gold if gold is not None else goldset.load()
    authored = authored if authored is not None else authored_store.load()

    approved: dict[str, list[dict]] = defaultdict(list)
    for record in gold["gold_relationship"]:
        approved[record["predicate"]].append(record)

    machine: dict[str, list[dict]] = defaultdict(list)
    for record in authored["gold_relationship"]:
        machine[record["predicate"]].append(record)

    usages = []
    for predicate in sorted(set(approved) | set(machine)):
        signed = sorted(approved[predicate], key=lambda r: r["id"])
        written = sorted(machine[predicate], key=lambda r: r["id"])
        rows = [*signed, *written]
        usages.append(
            PredicateUsage(
                predicate=predicate,
                approved_ids=tuple(r["id"] for r in signed),
                authored_ids=tuple(r["id"] for r in written),
                subject_types=tuple(sorted({observed_type(str(r["subject"])) for r in rows})),
                object_types=tuple(sorted({observed_type(str(r["object"])) for r in rows})),
            )
        )
    return tuple(usages)


def render(usages: tuple[PredicateUsage, ...]) -> str:
    approved_terms = [u for u in usages if u.is_approved]
    authored_terms = [u for u in usages if u.is_authored]
    new_terms = [u for u in usages if u.is_authored and not u.is_approved]
    out = [
        _HEADER.format(
            approved_terms=len(approved_terms),
            approved_count=sum(u.approved_count for u in usages),
            approved_singletons=sum(1 for u in approved_terms if u.approved_count == 1),
            authored_terms=len(authored_terms),
            authored_count=sum(u.authored_count for u in usages),
            new_terms=len(new_terms),
        )
    ]

    for usage in usages:
        lines = [f"\ntmk:{usage.predicate} a owl:ObjectProperty ;"]
        if usage.is_approved:
            lines.append("    a tmk:ApprovedRelation ;")
        if usage.is_authored:
            lines.append("    a tmk:AuthoredRelation ;")
        lines += [
            f'    rdfs:label "{_label(usage.predicate)}"@en-AU ;',
            "    rdfs:domain tmk:LegalMatter ;",
            "    rdfs:range tmk:LegalMatter ;",
        ]
        # Two counters, never one. `tmk:usageCount` keeps its meaning — the
        # signed count — so nothing reading it starts silently including
        # unreviewed records (ADR-0080 consequence 3, ADR-0091 consequence 4).
        lines.append(f"    tmk:usageCount {usage.approved_count} ;")
        lines.append(f"    tmk:authoredUsageCount {usage.authored_count} ;")
        for term in usage.subject_types:
            lines.append(f"    tmk:observedSubjectType {term} ;")
        for term in usage.object_types:
            lines.append(f"    tmk:observedObjectType {term} ;")
        for record_id in usage.approved_ids:
            lines.append(f'    tmk:usedBy "{record_id}" ;')
        shown = usage.authored_ids[:AUTHORED_USED_BY_LIMIT]
        for record_id in shown:
            lines.append(f'    tmk:authoredUsedBy "{record_id}" ;')
        lines.append(f"    rdfs:comment {_comment(usage)}@en-AU .")
        out.append("\n".join(lines))
    return "\n".join(out) + "\n"


def _comment(usage: PredicateUsage) -> str:
    parts = []
    if usage.is_approved:
        plural = "" if usage.approved_count == 1 else "s"
        sourced = "sourced to" if usage.approved_count == 1 else "every one sourced to"
        parts.append(
            f"Approved usage: {usage.approved_count} relationship{plural} "
            f"({', '.join(usage.approved_ids)}), {sourced} TMM/Part29."
        )
    else:
        parts.append(
            "NOT APPROVED VOCABULARY. No expert has used this term in a signed "
            "record; it exists because the corpus outside Part 29 states a "
            "relation the fourteen approved terms cannot express."
        )
    if usage.is_authored:
        plural = "" if usage.authored_count == 1 else "s"
        shown = usage.authored_ids[:AUTHORED_USED_BY_LIMIT]
        more = usage.authored_count - len(shown)
        tail = f", and {more} more" if more > 0 else ""
        parts.append(
            f"Authored usage: {usage.authored_count} relationship{plural} "
            f"({', '.join(shown)}{tail}), read by nobody."
        )
    return '"' + " ".join(parts).replace('"', '\\"') + '"'


def write(
    path: Path | None = None,
    *,
    gold: goldset.GoldSet | None = None,
    authored: authored_store.AuthoredSet | None = None,
) -> Path:
    path = path or RELATIONS_PATH
    path.write_text(render(collect(gold, authored)), encoding="utf-8")
    return path
