"""Generate `ontology/draft/relations.ttl` from the approved relationship register.

The closed predicate list is **derived, never authored**. Every term in it is
one an expert already used in an approved `eval/gold/relationships.yaml` record,
and the file records how many records use it and which ones. That is the whole
argument for generating it: a hand-written dictionary would be an agent choosing
the vocabulary, which is the one thing CLAUDE.md rule 1 forbids, and it would go
stale the first time a review round added a predicate.

What the generator refuses to do is as important as what it does. It does not
assert a narrow `rdfs:domain` or `rdfs:range` from observed usage. Under OWL 2
RL a domain assertion reclassifies every subject of the property, so inferring
`rdfs:domain tmk:LegalConcept` from three examples would manufacture
classifications from a sample size. The observed types are annotations; the
asserted domain and range are `tmk:LegalMatter`, which licenses nothing false.

Run: `tmk-ontology-relations --write`. A test asserts the committed file is
exactly what a regeneration produces, so the two cannot drift.
"""

from __future__ import annotations

import re
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path

from tm_knowledge.config import REPO_ROOT
from tm_knowledge.stage0 import goldset

__all__ = ["RELATIONS_PATH", "PredicateUsage", "collect", "render", "write"]

RELATIONS_PATH = REPO_ROOT / "ontology" / "draft" / "relations.ttl"

_HEADER = """\
@prefix tmk:     <https://data.ipaustralia.gov.au/tmk/ns/> .
@prefix tmkc:    <https://data.ipaustralia.gov.au/tmk/concept/> .
@prefix owl:     <http://www.w3.org/2002/07/owl#> .
@prefix rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs:    <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd:     <http://www.w3.org/2001/XMLSchema#> .
@prefix skos:    <http://www.w3.org/2004/02/skos/core#> .
@prefix prov:    <http://www.w3.org/ns/prov#> .
@prefix dcterms: <http://purl.org/dc/terms/> .

# GENERATED by tm_knowledge.ontology.relations from eval/gold/relationships.yaml.
# Do not hand-edit: a test compares this file against a regeneration.
# To add a predicate, have an expert approve a relationship that uses it.

<https://data.ipaustralia.gov.au/tmk/ns/relations>
    a owl:Ontology ;
    rdfs:label "TM-Knowledge — relation dictionary"@en-AU ;
    rdfs:comment \"\"\"The closed list of predicates extraction may propose.

Derived from the {count} approved relationships in `eval/gold/relationships.yaml`:
{terms} distinct predicates, of which {singletons} are used exactly once. That last
number is the one to read before treating this dictionary as settled — a term
seen once is a term whose boundaries nobody has tested.

Domain and range are `tmk:LegalMatter` throughout. The narrow types each
predicate has actually been seen with are annotations and infer nothing; see
tmk:LegalMatter in the legal-concepts module for why.\"\"\"@en-AU ;
    owl:imports <https://data.ipaustralia.gov.au/tmk/ns/legal-concepts> ;
    owl:versionInfo "draft — generated, not approved" .
"""

#: `GC-0001` -> Concept, `TMM/...` -> ManualChunk, and so on. Structural only:
#: it reads the id or ref grammar and makes no claim about what the thing means.
_TYPE_PATTERNS: tuple[tuple[str, str], ...] = (
    (r"^GC-[0-9]+$", "tmk:LegalConcept"),
    (r"^TMM/", "tmk:Chunk"),
    (r"^CASE/", "tmk:JudicialDecision"),
    (r"^(TMA|TMR)[0-9]{4}/", "tmk:LegislativeProvision"),
)


def observed_type(value: str) -> str:
    for pattern, term in _TYPE_PATTERNS:
        if re.match(pattern, value):
            return term
    return "tmk:LegalMatter"


def _label(predicate: str) -> str:
    """`mayGiveRiseTo` -> `may give rise to`. Mechanical, so it cannot editorialise."""
    return re.sub(r"(?<!^)(?=[A-Z])", " ", predicate).lower()


@dataclass(frozen=True)
class PredicateUsage:
    """One predicate, and every approved record that put it in the dictionary."""

    predicate: str
    record_ids: tuple[str, ...]
    subject_types: tuple[str, ...]
    object_types: tuple[str, ...]

    @property
    def count(self) -> int:
        return len(self.record_ids)


def collect(gold: goldset.GoldSet | None = None) -> tuple[PredicateUsage, ...]:
    """Every predicate in the approved set, with its usage. Sorted, so the
    generated file is byte-stable across runs."""
    gold = gold or goldset.load()
    records: dict[str, list[dict]] = defaultdict(list)
    for record in gold["gold_relationship"]:
        records[record["predicate"]].append(record)

    usages = []
    for predicate in sorted(records):
        rows = sorted(records[predicate], key=lambda r: r["id"])
        usages.append(
            PredicateUsage(
                predicate=predicate,
                record_ids=tuple(r["id"] for r in rows),
                subject_types=tuple(sorted({observed_type(str(r["subject"])) for r in rows})),
                object_types=tuple(sorted({observed_type(str(r["object"])) for r in rows})),
            )
        )
    return tuple(usages)


def render(usages: tuple[PredicateUsage, ...]) -> str:
    total = sum(usage.count for usage in usages)
    singletons = sum(1 for usage in usages if usage.count == 1)
    out = [_HEADER.format(count=total, terms=len(usages), singletons=singletons)]

    for usage in usages:
        lines = [
            f"\ntmk:{usage.predicate} a owl:ObjectProperty ;",
            "    a tmk:ApprovedRelation ;",
            f'    rdfs:label "{_label(usage.predicate)}"@en-AU ;',
            "    rdfs:domain tmk:LegalMatter ;",
            "    rdfs:range tmk:LegalMatter ;",
            f"    tmk:usageCount {usage.count} ;",
        ]
        for term in usage.subject_types:
            lines.append(f"    tmk:observedSubjectType {term} ;")
        for term in usage.object_types:
            lines.append(f"    tmk:observedObjectType {term} ;")
        for record_id in usage.record_ids:
            lines.append(f'    tmk:usedBy "{record_id}" ;')
        lines.append(
            f'    rdfs:comment "Approved usage: {usage.count} '
            f'relationship{"" if usage.count == 1 else "s"} '
            f'({", ".join(usage.record_ids)})."@en-AU .'
        )
        out.append("\n".join(lines))
    return "\n".join(out) + "\n"


def write(path: Path | None = None, *, gold: goldset.GoldSet | None = None) -> Path:
    path = path or RELATIONS_PATH
    path.write_text(render(collect(gold)), encoding="utf-8")
    return path
