"""Generate the ontology draft's status report.

Generated rather than written, for ADR-0042's reason and for the one S009
learned the hard way: a hand-derived analysis over an interlinked set is wrong
on arrival and stale by the next round. Every number below is counted from the
built graph, the shape run and the query run.

The report is deliberately organised around what the draft **cannot** do. A
demonstration that lists only its successes is a sales document, and the thing
being demonstrated here is a method whose whole value is that it says what it
does not know.
"""

from __future__ import annotations

from datetime import date
from pathlib import Path

from rdflib.namespace import OWL, RDF, SKOS

from tm_knowledge.config import REPO_ROOT
from tm_knowledge.ontology import ask as ask_module
from tm_knowledge.ontology import relations as relations_module
from tm_knowledge.ontology import rules as rules_module
from tm_knowledge.ontology import validate as validate_module
from tm_knowledge.ontology.build import build
from tm_knowledge.ontology.namespaces import APPROVED_GRAPH, SOURCE_GRAPH, TMK
from tm_knowledge.ontology.tbox import MODULES, load as load_tbox

__all__ = ["REPORT_PATH", "render", "write"]

REPORT_PATH = REPO_ROOT / "data" / "derived" / "reports" / "ontology.md"

_HEADER = """\
<!-- Generated by tm_knowledge.ontology.report. Do not hand-edit. -->

# The section 43 ontology draft — what it holds and what it cannot answer

**This is a draft, and nothing in `ontology/draft/` is approved.** The classes
and properties are a modelling proposal; the content under them is not. Every
concept, relationship, prohibition and question in the graph came out of
`eval/gold/`, where a named reviewer signed it — the ontology layer transforms
that content and authors none of it (CLAUDE.md rule 1).

Read section 5 first if you have five minutes. It is the list of things this
draft is not able to do, and it is the honest half of the demonstration.
"""


def _rule_state_lines(rule_set) -> str:
    """One line per rule saying who approved it and when, or what it waits on.

    Generated rather than written, because "neither is approved" was true when
    the paragraph was typed and stopped being true the moment the owner ruled on
    OQ-0004 — and a sentence in a generated report that has to be remembered is
    a sentence that goes stale (ADR-0068).
    """
    lines = []
    for rule in rule_set:
        state = "**approved**" if rule.is_approved else "**pending**"
        lines.append(f"- `{rule.rule_id}` — {state}. {rule.approved_by}")
    return "\n".join(lines)


def _fmt(rows: list[tuple], headers: tuple[str, ...]) -> str:
    out = ["| " + " | ".join(headers) + " |", "|" + "|".join("---" for _ in headers) + "|"]
    for row in rows:
        out.append("| " + " | ".join(str(cell) for cell in row) + " |")
    return "\n".join(out)


def render() -> str:
    dataset, build_report = build()
    tbox = load_tbox()
    approved = dataset.graph(APPROVED_GRAPH)
    source = dataset.graph(SOURCE_GRAPH)

    validation = validate_module.run(dataset)
    queries = ask_module.load_queries()
    coverage = ask_module.coverage(dataset, queries)
    rule_set = rules_module.load_rules()
    _dataset, rule_counts = rules_module.apply_rules(dataset, rule_set)

    predicates = relations_module.collect()
    classes = sorted(
        str(node).rsplit("/", 1)[-1]
        for node in tbox.subjects(RDF.type, OWL.Class)
        if str(node).startswith("https://data.ipaustralia.gov.au/tmk/ns/")
    )
    unpopulated = sorted(
        name
        for name in classes
        if not list(approved.subjects(RDF.type, TMK[name]))
        and not list(source.subjects(RDF.type, TMK[name]))
    )

    concepts_without_narrower_or_broader = [
        str(approved.value(node, TMK.goldRecord))
        for node in approved.subjects(RDF.type, TMK.LegalConcept)
        if not list(approved.objects(node, SKOS.broader))
        and not list(approved.objects(node, SKOS.narrower))
    ]

    parts = [_HEADER]

    parts.append(f"""
| | |
|---|---|
| Pinned snapshot | `{_pin(dataset)}` |
| Generated | {date.today().isoformat()} |
| Ontology modules | {len(MODULES)}, all draft |
| Classes declared | {len(classes)} |
| Predicates on the closed list | {len(predicates)}, derived from {sum(p.count for p in predicates)} approved relationships |
| Source graph | {build_report.triples['source']:,} triples over {build_report.chunks} chunks |
| Approved graph | {build_report.triples['approved']:,} triples — signed by a named expert |
| Authored graph | {build_report.triples.get('authored', 0):,} triples — **written by a machine, validated by nobody** |
| SHACL result | {len(validation.by_severity('defect'))} defects, {len(validation.by_severity('gap'))} gaps, {len(validation.by_severity('note'))} notes — exit {validation.exit_code} |
| Competency queries | {len(queries)} of {len(queries) + len(coverage['unqueried']) + len(coverage['deferred'])} questions |
""")

    parts.append("""
## 1. What is in the graph

Three named graphs, and the separation is the governance mechanism (ADR-0007).
`source` restates what upstream already recorded; `approved` restates what a
reviewer already signed; `authored` restates what a machine wrote and nobody has
read (ADR-0080). Nothing is in more than one.

**The two record stores are never added together.** A single figure would answer
the question a reader actually has — *how much of this has a person looked at* —
in the one direction that matters, and would do it silently. A larger authored
figure is not thereby a worse one; it is an unreviewed one, and that is a
different fact about the same rows.
""")
    parts.append(_fmt(
        [
            ("`source`", "chunks", build_report.chunks),
            ("`source`", "pages", build_report.pages),
            ("`source`", "provisions and units cited", build_report.provisions),
            ("`source`", "decisions cited", build_report.cases),
            ("`source`", "citations, reified with extraction and certainty", build_report.citations),
            ("`approved`", "concepts", build_report.concepts),
            ("`approved`", "relationships, each with a direct triple and an assertion", build_report.relationships),
            ("`approved`", "entity mentions", build_report.mentions),
            ("`approved`", "questions (competency, retrieval, search)", build_report.questions),
            ("`approved`", "prohibited uses", build_report.prohibited_uses),
            ("`authored`", "concepts", build_report.authored.concepts),
            ("`authored`", "relationships, each with a direct triple and an assertion",
             build_report.authored.relationships),
            ("`authored`", "entity mentions", build_report.authored.mentions),
            ("`authored`", "questions (competency, retrieval, search)",
             build_report.authored.questions),
            ("`authored`", "prohibited uses", build_report.authored.prohibited_uses),
        ],
        ("graph", "holds", "count"),
    ))
    if build_report.authored_refused:
        refused = ", ".join(sorted(build_report.authored_refused)[:12])
        parts.append(
            f"\n**{len(build_report.authored_refused)} authored record(s) were "
            "refused** and are in no graph: their envelopes do not validate, so "
            "nothing can say who wrote them or on what. `tmk-harness` names each "
            "one — refused, not dropped, because a silently dropped authored "
            "record is indistinguishable from one that was never written. "
            f"Ids: {refused}.\n"
        )

    parts.append(f"""
### The trust metadata survived

{build_report.citations} citations reached the graph as nodes rather than as bare edges, each
carrying upstream's `extraction` and `certainty` verbatim. That is what makes
CQ-0022 — *did the Manual's authors link that section themselves, or did we work
it out from the wording?* — a query rather than a shrug. Collapsing those two
fields would have destroyed the only thing separating an author's assertion from
an inference, and it cannot be recovered afterwards (CLAUDE.md rule 3).

{build_report.unresolved_citations} of those citations land on nothing this corpus holds. They are recorded
as unresolved, never repaired: CQ-0020 asks for exactly this list.
""")

    parts.append("""
## 2. What the shapes stop

`shapes/` runs as the gate before anything publishes. Most of these are the
roadmap's own starting rule set. Two are not, and they are the interesting ones:
**PU-0004** is the reviewer's own prohibition expressed as a constraint that
blocks publication rather than a test that reports afterwards, and **the
not-label check** is a constraint SKOS has no vocabulary for at all.
""")
    parts.append(_fmt(
        [
            ("PU-0004 — authority conflation", "`shapes/authority.ttl`",
             "a proposition whose words are in a practice passage and which is attributed to the Act",
             "`tests/unit/test_shapes_fire.py::test_pu_0004_authority_conflation_fires`"),
            ("Practice and law are disjoint", "`shapes/authority.ttl`",
             "a node typed both `ManualInstruction` and `LegislativeProvision`",
             "`test_disjoint_authority_fires`"),
            ("Every approved proposition has a source passage", "`shapes/provenance.ttl`",
             "an assertion with no passage, method, reviewer or date",
             "`test_unsigned_assertion_fires_on_every_missing_field`"),
            ("No cycles in broader/narrower", "`shapes/vocabulary.ttl`",
             "a concept that is its own ancestor",
             "`test_broader_cycle_fires`"),
            ("A not-label is not also a label", "`shapes/vocabulary.ttl`",
             "a term recorded at once as meaning a concept and as never meaning it",
             "`test_not_label_that_is_also_a_label_fires`"),
            ("Every inference names its rule", "`shapes/inference.ttl`",
             "a derived assertion that cannot explain itself",
             "`test_unexplained_inference_fires`"),
            ("Reasoning stays inside its bounds", "`shapes/inference.ttl`",
             "a rule deriving an evidentiary proposition",
             "`test_bounded_reasoning_fires_on_a_derived_evidentiary_proposition`"),
            ("Superseded material carries a status date", "`shapes/temporal.ttl`",
             "a superseded passage with no date",
             "`test_undated_supersession_fires`"),
        ],
        ("constraint", "file", "fires on", "proof it fires"),
    ))
    parts.append(f"""
Every one has a fixture built to violate it, because *an untested shape that
never matches anything is worse than no shape: it reads as coverage*
(`shapes/README.md`). The PU-0004 fixture carries a conforming twin — the same
words, from the same passage, honestly attributed — and the shape must leave it
alone. A constraint that fired on both would pass a fires-test and be useless.

Against the real content: **{len(validation.by_severity('defect'))} defects, {len(validation.by_severity('gap'))} gaps,
{len(validation.by_severity('note'))} notes.** The notes are all one thing — a concept whose not-label is
another concept's preferred label, which is what a not-label is *for* and is
reported so the pairs are visible.
""")

    lines = ["", "## 3. What it answers", "",
             "One query per competency question that a graph query can answer, named for",
             "the question. Each carries a `limits:` line saying what it has **not**",
             "established — a query that returns rows always looks like an answer.", ""]
    lines.append(_fmt(
        [(q.question_id, q.answers) for q in queries],
        ("question", "answers"),
    ))
    parts.append("\n".join(lines))

    parts.append(f"""
The three worth running first:

- **CQ-0017** reproduces `tmk-recon`'s Part distribution exactly and adds a
  column recon does not have: how many of each Part's citations the Manual's
  authors wrote themselves, and how many are upstream's inference from a bare
  "section 43". Part 47, Part 12, Part 23 and Part 31 are carried entirely by
  inferred edges — which makes "this Part needs reviewing" a weaker claim there
  than the count alone suggests.
- **CQ-0023** returns a blank first row on purpose. The proposition that a
  connotation must arise from the mark itself is stated in `TMM/Part29/2/2/3`,
  and that passage cites no decision at all. An inner join would have hidden
  that by returning only the rows that happened to have cases.
- **CQ-0012** returns prohibitions and stops. The question is *is the connotation
  in this trade mark strong enough to warrant a ground for rejection* — an
  evaluative judgement for the decision maker — and the graph's answer is the
  three outputs that would answer it and must not be produced.

**Modality, from CQ-0024:** {_modality_line(approved)}. The blank is not a
default and is not filled: whether a "may" is possibility or permission is a
legal reading (guide §5.4).
""")

    approved_rules = [rule for rule in rule_set if rule.is_approved]
    pending_rules = [rule for rule in rule_set if not rule.is_approved]
    parts.append(f"""
## 4. What it infers, and under what conditions

{len(rule_set)} CONSTRUCT rules: **{len(approved_rules)} approved, {len(pending_rules)} pending.**
Stage 9 requires a person to approve every reasoning template before deployment.
The `approved-by` line in each file is the approval record, and
`tm_knowledge.ontology.rules` reads it rather than trusting the query — a rule
body may not set its own review status, and an unapproved rule's output is
stamped `reviewStatus "candidate"` and `requiresHumanReview true`. Approved or
not, output goes to `graph/inferred.ttl` and nowhere else: approval says an
inference may be relied on, it does not make it a signed record.

{_rule_state_lines(rule_set)}
""")
    parts.append(_fmt(
        [
            (
                rule.rule_id,
                getattr(rule_counts.get(rule.rule_id), "assertions", 0),
                getattr(rule_counts.get(rule.rule_id), "triples", 0),
                rule.basis.split(".")[0][:70],
            )
            for rule in rule_set
        ],
        ("rule", "conclusions", "triples", "stands on"),
    ))
    parts.append(
        "**Read the first number, not the second.** *Conclusions* is how many things the "
        "rule concluded; *triples* counts the provenance carried with them, roughly eight "
        "or fourteen per conclusion. Quoting the triple count as if it were the number of "
        "findings is how the owner came to be asked to review 71 flagged passages when "
        "there are five (Q-44)."
    )
    parts.append("""
RULE-0001 is GX-0001 made executable. It finds the passages that carry both
quoted legislative text and the Registrar's own practice — the mixture that
makes CQ-0001's caveat bite, because the Manual quotes s 43 in full inside
`TMM/Part29/1#1` and an answer can therefore appear to cite the Act while having
read only the Manual. It finds `TMM/Part29/1#1` among them.

Each rule has both tests the standard requires: one proving it fires, one
proving it stays quiet on the near case. RULE-0001's near-miss is a chunk with
practice mentions and no quoted provision — most of the corpus looks like that,
and a rule that fired there would make the flag mean nothing.
""")

    unmatched = build_report.unmatched_concept_labels
    boundaries = build_report.boundary_concept_labels
    untyped = build_report.concepts - build_report.concept_types
    parts.append(f"""
## 5. What it cannot do — read this part

**{untyped} of {build_report.concepts} concepts are not sorted into a group.** `GroundOfRefusal`,
`LegalTest`, `RelevantFactor` and `Exception` fill only from signed records in
`eval/gold/concept-types.yaml`, and {build_report.concept_types} concepts have one. Deciding that
*connotation* is a LegalTest rather than a RelevantFactor is a legal judgement,
so nothing here fills it. What changed on 2026-09-08 is that there is now
somewhere for the answer to go and a pass to collect it — `tmk-typing` renders
the whole vocabulary as one sheet of dropdowns (OQ-0001, ADR-0071). Until it
comes back this is the single largest gap in the draft.

**No concept has a definition.** The approved records carry definition
*sources* — the passages the meaning is drawn from — and no definition text, so
the graph carries sources and no text. `skos:definition` appears nowhere.

**{len(unpopulated)} declared classes hold nothing**: {", ".join(f"`{name}`" for name in unpopulated[:14])}{"…" if len(unpopulated) > 14 else ""}.
The whole evidence module is among them, and deliberately: the section 43
material is about what a sign connotes, not about what an applicant files.

**{len(concepts_without_narrower_or_broader)} of {build_report.concepts} concepts sit outside any hierarchy** — no broader, no narrower.
A vocabulary that is mostly flat is a list with extra steps, and the hierarchy is
where a retrieval system gets its generalisation.

**{len(unmatched)} competency questions name a concept the vocabulary does not hold**: {", ".join(f"`{item}`" for item in unmatched)}.
Either the vocabulary is short a concept, or the question names one by a variant
nobody recorded as an alt label. Both are worklist items.

**{len(boundaries)} name a concept it deliberately excludes, which is the opposite of a gap**: {", ".join(f"`{item}`" for item in boundaries) or "none"}.
The distinction is new, and `CQ-0007:deceptively similar` is why. Three approved
concepts carry that term as a **not-label**, and CQ-0007 asks *"confusion between
my mark and someone else's — which section is that?"*, whose answer is section 44.
Counted as a missing concept it reported a miss on every measurement that used
the question. The owner ruled on OQ-0002: *"It belongs to section 44 — keep it
out, the question is using it as a boundary marker"* (ADR-0075). Neither approved
record changed; what changed is that the graph now joins them, via
`tmk:expectsBoundaryLabel` and `tmk:testsBoundaryOf`.

**Six of the fourteen predicates are used exactly once.** A term seen once is a
term whose boundaries nobody has tested. `GR-0008`'s own note says
`requiresElement` "reads plausibly and says the wrong thing" on that record, and
it was left in deliberately as an example.

**Domain and range are `tmk:LegalMatter` everywhere.** The approved
relationships do not agree on narrower types — `requiresElement` runs
Provision→Concept, Concept→Concept and Concept→Provision — and under OWL RL a
narrow domain assertion silently reclassifies every subject of the property.
The types each predicate has actually been seen with are recorded as annotations
that infer nothing. Tightening them is an expert ruling.

**Point-in-time questions are unanswerable and will stay that way** under this
snapshot strategy. There is no corpus-level version stamp; the amendment history
is the upstream repository's git history (Q-05). CQ-0014 carries that limitation.

**No decision text exists anywhere in the programme.** "Which cases interpret
this test" is answerable; "what did the court hold" is not (Q-11). PU-0005 is the
output that pretends otherwise.

**{len(coverage['deferred'])} competency questions need a stage that does not exist**: {"; ".join(coverage['deferred'])}.
A search question is answered by a ranked index and a retrieval question by a
generated answer over retrieved passages. Neither is a SPARQL result, and writing
a query that returned rows for them would be measuring the wrong thing while
looking like coverage.

**{len(coverage['unqueried'])} has no query and could have one**: {", ".join(coverage['unqueried']) or "none"}.
""")

    parts.append("""
## 6. What this demonstrates, stated plainly

The claim is not that the ontology is finished. It is that the method works end
to end on real content, and that the places it breaks are visible rather than
hidden:

1. **Expert-approved records become a graph without an agent authoring
   anything.** Every node traces to a record, a reviewer and a date.
2. **The practice/law distinction survives into query output.** Every answer
   that names a passage names its authority kind, and a shape blocks the
   attribution error the reviewer flagged.
3. **A prohibition became a constraint.** PU-0004 was a paragraph in a YAML
   file; it is now something that stops a publish, with a fixture proving it
   fires and a conforming twin proving it is selective.
4. **The gaps are countable.** The empty taxonomy, the flat vocabulary, the
   once-used predicates and the missing definitions are all numbers in section
   5, produced by the same run that produced the successes.

The next unit of expert time with the largest effect is **typing the 52 concepts
into the four subclasses** — it is one pass over a list, it needs no new records,
and it is what turns a flat vocabulary into a hierarchy the retrieval stages can
generalise over.
""")
    return "\n".join(parts).replace("\n\n\n", "\n\n") + "\n"


def _pin(dataset) -> str:
    from tm_knowledge.upstream.pin import Pin

    pin = Pin.load()
    return (
        f"{pin.repo} @ {pin.commit[:12]} "
        f"({pin.manual_extractor_version}, {pin.legislation_extractor_version})"
    )


def _modality_line(approved) -> str:
    from collections import Counter

    counts: Counter[str] = Counter()
    for node in approved.subjects(RDF.type, TMK.ApprovedAssertion):
        if approved.value(node, TMK.assertionPredicate) is None:
            continue
        modality = approved.value(node, TMK.modality)
        counts[str(modality) if modality else "not supplied"] += 1
    return ", ".join(f"{count} `{name}`" for name, count in sorted(counts.items()))


def write(text: str | None = None, path: Path | None = None) -> Path:
    path = path or REPORT_PATH
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text if text is not None else render(), encoding="utf-8")
    return path
