"""Corpus reconnaissance for the scope decision (parallel track P6).

Machine-derived, purely factual reports about the pilot area, so the boundary
decision is made against numbers instead of impressions. **Every output is a
count or a listing of what upstream already records.** Nothing here interprets
anything, nothing proposes a boundary, and the report says so on its face.

That disclaimer is not politeness. A report that reads as a recommendation is a
draft of the expert's decision, and a plausible draft anchors the reviewer —
which is the failure CLAUDE.md rule 1 and the parallel track's §3 both exist to
prevent. The reports say what the corpus contains. What is in scope is the
expert's answer to a question this file cannot ask.
"""

from __future__ import annotations

from collections import Counter
from dataclasses import dataclass
from datetime import datetime, timezone

from tm_knowledge.stage0.worksheet import ScopeRule, select
from tm_knowledge.upstream.loader import Corpus

#: The pilot provision (ADR-0013, human decision).
PILOT_PROVISION = "TMA1995/s43"

HEADER = """<!-- Generated by tm_knowledge.stage0.recon. Do not hand-edit. -->

# Corpus reconnaissance — {provision}

**These are derived counts, not a scope proposal.** Every number below is a
count of what `manual-XtrACTor` already records. Nothing here interprets the
corpus, proposes a boundary, or says what ought to be in scope — those are
expert judgements and this file cannot make them (CLAUDE.md rule 1).

| | |
|---|---|
| Pinned snapshot | `{repo}` @ `{commit}` |
| Extractor versions | `{manual_version}`, `{legislation_version}` |
| Generated | {generated} |
"""


@dataclass(frozen=True, slots=True)
class Recon:
    """The factual picture of a candidate pilot area."""

    provision: str
    citing_chunks: tuple[str, ...]
    pages: tuple[str, ...]
    with_page_mates: tuple[str, ...]
    by_part: Counter
    by_kind: Counter
    by_extraction: Counter
    by_certainty: Counter
    unresolved_in_scope: tuple[str, ...]
    ambiguous_in_scope: tuple[tuple[str, str], ...]
    cases_cited: tuple[tuple[str, str, int], ...]
    words_citing: int
    words_with_page_mates: int


def reconnoitre(corpus: Corpus, provision: str = PILOT_PROVISION) -> Recon:
    rule = ScopeRule(provision=provision)
    citing = corpus.chunks_citing(provision)
    selected = select(corpus, rule)

    by_part: Counter = Counter()
    by_kind: Counter = Counter()
    by_extraction: Counter = Counter()
    by_certainty: Counter = Counter()
    cases: Counter = Counter()
    citations: dict[str, str] = {}
    ambiguous: list[tuple[str, str]] = []

    for chunk in citing:
        by_part[chunk.part_id] += 1
        by_kind[chunk.kind] += 1
        for edge in chunk.provisions:
            if not rule.matches(edge.id):
                continue
            by_extraction[edge.extraction] += 1
            by_certainty[edge.certainty or "—"] += 1
            if edge.needs_a_human:
                ambiguous.append((chunk.chunk_ref, edge.id))

    known = corpus.provisions.keys() | corpus.units.keys()
    unresolved = sorted(
        {
            edge.id
            for chunk in selected
            for edge in chunk.provisions
            if edge.id.split("/", 1)[0] in {"TMA1995", "TMR1995"} and edge.id not in known
        }
    )

    for chunk in selected:
        for edge in chunk.cases:
            cases[edge.id] += 1
            citations[edge.id] = edge.citation

    return Recon(
        provision=provision,
        citing_chunks=tuple(chunk.chunk_ref for chunk in citing),
        pages=tuple(sorted({chunk.page_ref for chunk in citing})),
        with_page_mates=tuple(chunk.chunk_ref for chunk in selected),
        by_part=by_part,
        by_kind=by_kind,
        by_extraction=by_extraction,
        by_certainty=by_certainty,
        unresolved_in_scope=tuple(unresolved),
        ambiguous_in_scope=tuple(sorted(ambiguous)),
        cases_cited=tuple(
            (case_id, citations[case_id], count) for case_id, count in sorted(cases.items())
        ),
        words_citing=sum(len(chunk.text.split()) for chunk in citing),
        words_with_page_mates=sum(len(chunk.text.split()) for chunk in selected),
    )


def _volume_table(recon: Recon, corpus: Corpus) -> str:
    """The number that turns 'which Parts are in scope' into a costed question.

    Annotation rate is deliberately *not* asserted here — nobody has measured
    how long an examiner takes over a chunk of this corpus, and inventing a
    figure would put a made-up number in front of a real decision. Words are
    reported; hours are the owner's arithmetic once a rate is known.
    """
    total = len(corpus.chunks)
    rows = [
        ("Chunks citing the provision or a unit beneath it", len(recon.citing_chunks)),
        ("Pages holding at least one of those", len(recon.pages)),
        ("Chunks once page-mates are included (ADR-0022's rule)", len(recon.with_page_mates)),
    ]
    lines = ["| Candidate rule | Chunks | Share of corpus | Words |", "|---|---:|---:|---:|"]
    for label, count in rows:
        words = (
            recon.words_citing
            if "citing" in label
            else recon.words_with_page_mates if "page-mates" in label else ""
        )
        share = f"{count / total:.1%}" if "Pages" not in label else "—"
        lines.append(f"| {label} | {count:,} | {share} | {words if words else '—':,} |"
                     if isinstance(words, int) and words
                     else f"| {label} | {count:,} | {share} | — |")
    return "\n".join(lines)


def render(recon: Recon, corpus: Corpus, *, generated: str | None = None) -> str:
    """The report, as Markdown. `generated` is injectable for the same reason as
    the worksheet's: everything but the date must be a function of the pin."""
    pin = corpus.pin
    out = [
        HEADER.format(
            provision=recon.provision,
            repo=pin.repo,
            commit=pin.commit,
            manual_version=pin.manual_extractor_version,
            legislation_version=pin.legislation_extractor_version,
            generated=generated or datetime.now(timezone.utc).strftime("%Y-%m-%d"),
        ),
        "\n## 1. Volume, per candidate rule\n",
        _volume_table(recon, corpus),
        (
            "\n\nThe third row is the rule ADR-0022 sets for the Pass B worksheet. "
            "It is deliberately over-inclusive and it is **not** the pilot scope; "
            "the boundary is still the expert's to draw.\n"
        ),
        "\n## 2. Where the citing chunks sit\n",
        "\n| Part | Chunks |\n|---|---:|",
    ]
    for part, count in sorted(recon.by_part.items(), key=lambda kv: (-kv[1], kv[0])):
        out.append(f"| {part} | {count} |")
    out.append("\n\n| Chunk kind | Chunks |\n|---|---:|")
    for kind, count in sorted(recon.by_kind.items()):
        out.append(f"| `{kind}` | {count} |")
    out.append(
        "\n\n`annex` and `landing` chunks are counted separately because the corpus "
        "is lopsided — 725 of its 2,460 chunks are annex material — and retrieval "
        "that treats all chunks alike surfaces a lot of it (Q-10).\n"
    )

    out.append("\n## 3. How the edges were found\n")
    out.append("\n| `extraction` | Edges |\n|---|---:|")
    for value, count in sorted(recon.by_extraction.items()):
        out.append(f"| `{value}` | {count} |")
    out.append("\n\n| `certainty` | Edges |\n|---|---:|")
    for value, count in sorted(recon.by_certainty.items()):
        out.append(f"| `{value}` | {count} |")
    out.append(
        "\n\n`href` is the Manual's authors linking the provision themselves; `regex` "
        "is upstream reading it out of prose. `default` is upstream's inference from "
        "a bare 'section 43', not a statement by IP Australia. None of these is "
        "collapsed anywhere in this repo (Q-07).\n"
    )

    out.append("\n## 4. In-scope refs that resolve to nothing\n")
    if recon.unresolved_in_scope:
        out.append(
            f"\n{len(recon.unresolved_in_scope)} distinct refs cited from the selected "
            "chunks land on no provision this corpus holds. Worth seeing **before** "
            "gold records are built on one — this is where the s 41 renumbering trap "
            "lives (Q-06).\n"
        )
        for ref in recon.unresolved_in_scope:
            out.append(f"- `{ref}`")
    else:
        out.append("\nNone.")

    out.append("\n\n## 5. Ambiguous edges in scope\n")
    if recon.ambiguous_in_scope:
        out.append(
            f"\n{len(recon.ambiguous_in_scope)} edges carry `certainty: ambiguous` — "
            "several instruments of that kind were in scope and upstream refused to "
            "choose. They are recorded as ambiguous and never corrected; an ambiguous "
            "edge is a reason to put a chunk in front of a human, never a reason to "
            "drop it (Q-07, ADR-0022).\n"
        )
        for chunk_ref, provision_id in recon.ambiguous_in_scope:
            out.append(f"- `{chunk_ref}` → `{provision_id}`")
    else:
        out.append("\nNone matching the provision.")

    out.append("\n\n## 6. Cases cited from the selected chunks\n")
    out.append(
        f"\n{len(recon.cases_cited)} distinct decisions are cited. **Citation level "
        "only** — no decision text exists anywhere in the programme, so 'which cases "
        "interpret this test' is answerable and 'what did the court hold' is not "
        "(Q-11).\n"
    )
    out.append("\n| Case | Citation | Mentions |\n|---|---|---:|")
    for case_id, citation, count in sorted(recon.cases_cited, key=lambda row: -row[2]):
        out.append(f"| `{case_id}` | {citation} | {count} |")

    out.append("\n\n---\n\n*Derived counts. Not a scope proposal.*\n")
    return "\n".join(out)
